### ISSUE TITLE
Support for "Status Filter" in View

### ISSUE THREAD

**Issue by Spenser309** [jenkinsci/configuration-as-code-plugin#1031]
### Feature Request

Please support the "Status Filter" in view configuration. Currently I cannot find support for this. I want to do something like the following to enable showing only currently active PRs in a build wall.
 
```
jenkins:
  primaryView:
    all:
      name: "all"
  views:
  - all:
      name: "all"
  - buildMonitor:
      includeRegex: ".*(PR-.*|master)"
      name: "wall"
      recurse: true
      title: "wall"
      statusFilter: enabled  <- new option.
```
