### ISSUE TITLE
Add YAML merge strategy to meet different use cases

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkinsci/configuration-as-code-plugin#1194]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

It will throw an exception if there's a merge conflict now. It's better if this behavior can be choose by the end-user. We can consider some cases below:

- throw an exception
- giving a warning (administrator monitor or other places)
- accept the value according to the loading order
  - accept the first one
  - accept the last one

**Comment by LinuxSuRen** [comment]
I'd like to do it. If you have any ideas about this feature, please let me know.

**Comment by timja** [comment]
Snakeyaml merge docs are here:
https://bitbucket.org/asomov/snakeyaml/wiki/Documentation

**Comment by LinuxSuRen** [comment]
@timja Thanks for providing the tech information. I'm thinking about the design details. Once I finished the design, I'll start it.

**Comment by rbywater** [comment]
Just wondering what the status of this issue & the related PR is? I'm not sure if things have changed recently since this issue was raised as if I have the following in two separate files I don't get an exception however its the last-one wins and so in the following example readonly only has user2 in it, and not user1. It would be nice to be able to say add the two together which I *think* is what the related PR was intending to allow?

00_config.yaml: 
```yaml
jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            assignments:
              - "user1"
```
99_config.yaml:
```yaml
jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "readonly"
            assignments:
              - "user2"
```
