### ISSUE TITLE
"slave" has been deprecated terminology since Jenkins 2

### ISSUE THREAD

**Issue by rtyler** [jenkinsci/configuration-as-code-plugin#121]
I noticed in the examples in the readme this snippet:

```yaml
jenkins:
  securityRealm:
    (...)

  nodes:
    slave:
      name: "static-slave"
      remoteFS: "/home/jenkins"
      launcher: "jnlp"
```

Since this is early in the project, can usage of "slave" be replaced with "agent" in the API to match the existing terminology used since Jenkins 2.0?

It would be a big step backwards for such an important project to adopt the term.
