### ISSUE TITLE
Kubernetes plugin error Item isn't a sequence.

### ISSUE THREAD

**Issue by KoniAnastasia** [jenkinsci/configuration-as-code-plugin#1217]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [x ] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [x ] Jenkins version
- [x ] Plugin version
- [ ] OS
- [ ] Reproduction steps

### Description

- Asked the question in Gitter chat but got no response.

-  Jenkins version: 2.190.3

- Plugin versions: kubernetes:1.20.2, configuration-as-code:1.33

I am trying to setup kubernetes plugin with Jcasc in the values of helm chart stable/jenkins. I get the error, Item isn't a sequence. I suspected it might be indentation error so I run yamllint but I have no indentation error. I read issue #933 but it was an indentation quirk with credentials. I tried to supply four spaces in my indentation to see if it fixed the problem but it didn't.

Kubernetes plugin config:

```
      kubernetes_plugin: |
        jenkins:
          location:
            url: "http://jenkins-master:8080"
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                skipTlsVerify: true
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins-master:8080"
                jenkinsTunnel: "jenkins-master-agent:50000"
                connectTimeout: 0
                readTimeout: 0
                containerCap: 10
                maxRequestsPerHost: 32
                waitForPodSec: 600
                templates:
                  - name: "default"
                    namespace: "default"
                    label: "jenkins-pod"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/jnlp-slave:3.35-3-alpine"
                        alwaysPullImage: false
                        workingDir: "/home/jenkins/agent"
                        ttyEnabled: false
                        args: "${computer.jnlpmac}${computer.name}"
                        resourceRequestCpu: "500m"
                        resourceLimitCpu: "1000m"
                        resourceRequestMemory: "1Gi"
                        resourceLimitMemory: "2Gi"
                    imagePullSecrets: "artifactory-registry"
```
Jenkins-master container log:
```
SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
12/5/2019 11:33:10 AM io.jenkins.plugins.casc.ConfiguratorException: Item isn't a Sequence
12/5/2019 11:33:10 AM at io.jenkins.plugins.casc.model.CNode.asSequence(CNode.java:22)
12/5/2019 11:33:10 AM at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:341)
12/5/2019 11:33:10 AM at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:270)
12/5/2019 11:33:10 AM Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to save PodTemplate{, nodeUsageMode=EXCLUSIVE, workspaceVolume=EmptyDirWorkspaceVolume [memory=false]}
```
