### ISSUE TITLE
Creating Jenkins users with E-mail and Full Name

### ISSUE THREAD

**Issue by P0sa** [jenkinsci/configuration-as-code-plugin#1254]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

It is currently possible to create jenkins users like this:

```
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
         - id: "foo"
           password: "bar"
```
What I am missing here is an entry for an E-mail and a Full Name, exactly like it is, when creating a user via the Jenkins WebUI. Would be great if those could be added! 
![Screenshot from 2020-01-22 16-25-17](https://user-images.githubusercontent.com/23658926/72907269-e1414900-3d33-11ea-83bd-cce91dcd20bb.png)
