### ISSUE TITLE
cucumber-slack-notifier plugin - configurable?

### ISSUE THREAD

**Issue by jamiejackson** [jenkinsci/configuration-as-code-plugin#1271]
### Your checklist for this issue

- [x] Jenkins version:  - 2.204.2
- [x] Plugin version - 1.35
- [x] OS - Docker image (Alpine): `jenkins/jenkins:lts-alpine`

### Description

Please describe your issue here.

Is it possible to configure this plugin with CasC?

GUI:

![image](https://user-images.githubusercontent.com/479475/74189718-e7ce2c80-4c1e-11ea-8e7d-5d119b917ad6.png)

My (failed) attempt:

```yml
unclassified:
  cucumberSlack:
    webHookEndpoint: https://hooks.slack.com/services/XYXYXYXYXYXYXYXYXYXYXYX
```
