### ISSUE TITLE
empty GitLab connection is created in addition the one defined in jenkins.yml

### ISSUE THREAD

**Issue by choeffer** [jenkinsci/configuration-as-code-plugin#1272]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version v2.204.2

- [x] Plugin version v1.35

- [x] OS Fedora 31 Cloud Base

### Description

An empty GitLab connection is created in addition to the one defined in jenkins.yml, see

![empty_connection](https://user-images.githubusercontent.com/33625292/74419771-af129b00-4e4a-11ea-86b6-e23d6de0ed79.png)

Adding credentials is working fine and "Test Connection" is reporting "Success".

The empty connection also gets exported by JCasC, see

```
unclassified:
  gitLabConnectionConfig:
    connections:
    - apiTokenId: "123"
      clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      name: "Gitlab"
      readTimeout: 30
      url: "https://gitlab.example.com"
    - clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      readTimeout: 10
```

If I can provide any further useful information, please let me know.
