### ISSUE TITLE
dumb slave agent configuration not selecting credentials

### ISSUE THREAD

**Issue by gogskrish** [jenkinsci/configuration-as-code-plugin#130]
CASC is adding the below agent in jenkins, However the "credentialsId" is not working. The credential ID is not selected in the UI.   

```yml
nodes:
    - dumb:
        labelString: "dockerce_build_vm"
        mode: NORMAL
        name: "dockerce_build_vm"
        remoteFS: "/home/jenkins"
        launcher:
          SSHLauncher:
            host: "1.1.1.1"
            port: 22
            credentialsId: jenkinsagentsshkey
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
               ManuallyTrustedKeyVerificationStrategy:
                  requireInitialManualTrust: True
```

**Comment by MadsNielsen** [comment]
hi @gogskrish I think your issue will be fixed with version 1.26 of the ssh slaves plugin which @oleg-nenashev has release. I think your issues relates to https://github.com/jenkinsci/configuration-as-code-plugin/issues/112

**Comment by lanwen** [comment]
as workaround it's possible to define `creds` node before `jenkins` in yaml.

**Comment by gogskrish** [comment]
I tried that. but it did not help

**Comment by jcrben** [comment]
fyi, ssh credentials seems to be working well for for me running from docker and jenkins version 2.129 - my jenkins.yaml file looks something like this:
```
jenkins:
  authorizationStrategy: unsecured
  nodes:
    - permanent:
        labelString: "test1"
        mode: NORMAL
        name: "test1"
        remoteFS: "/home/user1"
        launcher:
          SSHLauncher:
            host: "192.168.0.2"
            port: 22
            credentialsId: ssh_with_passprase_provided
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: ssh_with_passprase_provided
              username: root
              description: "SSH passphrase with private key file. Private key provided"
              privateKeySource:
                directEntry:
                  privateKey: ${SSH_PRIVATE_KEY}
```

with pluins.txt like this:
```
analysis-core:1.95
apache-httpcomponents-client-4-api:4.5.5-3.0
bouncycastle-api:2.16.0
build-timeout:1.19
conditional-buildstep:1.3.6
email-ext:2.62
envinject:2.1.5
external-monitor-job:1.6
jenkins-multijob-plugin:1.13
git:3.6.3
github-api:1.90
matrix-project:1.7.1
matrix-auth:2.2
pipeline-model-definition:1.3.1
ssh-agent:1.15
ssh-credentials:1.14
ssh-slaves:1.26
windows-slaves:1.3.1
configuration-as-code:experimental
command-launcher:latest
jdk-tool:latest
```
