### ISSUE TITLE
Invalid configuration elements for type class jenkins.model.Jenkins : credentials. 

### ISSUE THREAD

**Issue by samitkumarpatel** [jenkinsci/configuration-as-code-plugin#1331]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ x] Jenkins version
2.204.5
- [x ] Plugin version
1.36
- [ x] OS
Mac OS (Jenkins running on a docker container)

### Description
while pointing a URL on `Path or URL` , which returns a valid jankins.yml like below , Gives me a validation error in the Jenkins UI (Image attached)
![image](https://user-images.githubusercontent.com/7632269/77115417-90498a80-6a2e-11ea-8029-1791233d308e.png)

The URL responds Below details:
```
---
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 1
  credentials:
    system:
      domainCredentials:
        - credentials:
            - usernamePassword:
                id: "bb_token"
                password: "${BB_ACCESS_TOKEN}"
                scope: GLOBAL
                username: "samitkumar.patel@maersk.com"
            - usernamePassword:
                id: "nexus_token"
                password: "${NEXUS_ACCESS_TOKEN}"
                scope: GLOBAL
                username: "Samitkumar.Patel"
            - string:
                id: "mdev_sonarqube_token"
                scope: GLOBAL
                secret: "${SONARQUBE_TOKEN}"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "samit"
          password: "XYZ123"
        - id: "other"
          password: "XYZ123"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            pattern: ".*"
            permissions:
              - "Job/Move"
              - "Job/Build"
              - "Lockable Resources/View"
              - "Credentials/Delete"
              - "Credentials/ManageDomains"
              - "Lockable Resources/Unlock"
              - "View/Create"
              - "Agent/Configure"
              - "Job/Read"
              - "Credentials/Update"
              - "Agent/Create"
              - "Job/Delete"
              - "Agent/Build"
              - "View/Configure"
              - "Lockable Resources/Reserve"
              - "Agent/Provision"
              - "SCM/Tag"
              - "Job/Create"
              - "Job/Discover"
              - "Credentials/View"
              - "Agent/Connect"
              - "Agent/Delete"
              - "Run/Replay"
              - "Agent/Disconnect"
              - "Run/Delete"
              - "Job/Cancel"
              - "Overall/Read"
              - "Run/Update"
              - "Credentials/Create"
              - "Overall/Administer"
              - "View/Delete"
              - "Job/Configure"
              - "Job/Workspace"
              - "View/Read"
            assignments:
              - "root"
              - "samit"
          - name: "user"
            pattern: ".*"
            permissions:
              - "Lockable Resources/View"
              - "Job/Build"
              - "SCM/Tag"
              - "Lockable Resources/Unlock"
              - "Job/Discover"
              - "Job/Read"
              - "Run/Replay"
              - "Run/Delete"
              - "Job/Cancel"
              - "Overall/Read"
              - "Run/Update"
              - "Job/Workspace"
              - "View/Read"
              - "Lockable Resources/Reserve"
            assignments:
              - "other"
  nodes:
    - permanent:
        labelString: "jnlpSlave"
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
        name: "jnlpSlave"
        nodeDescription: "jnlpSlave"
        numExecutors: 3
        remoteFS: "/tmp"
        retentionStrategy: "always"
    - permanent:
        labelString: "jnlpDockerSlave"
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
        name: "jnlpDockerSlave"
        nodeDescription: "jnlpDockerSlave"
        numExecutors: 3
        remoteFS: "/tmp"
        retentionStrategy: "always"
```

-- | --
