### ISSUE TITLE
autorizationStrategy projectMatrix not applied

### ISSUE THREAD

**Issue by tomlankhorst** [jenkinsci/configuration-as-code-plugin#1345]
Part of my configuration looks like this: 

```yaml
  authorizationStrategy:                                                                                                                                                                                           
    projectMatrix:                                                                                                                                                                                                 
      permissions:                                                                                                                                                                                                 
      - "Agent/Build:anonymous"                                                                                                                                                                                    
      - "Overall/Administer:admin"                                                                                                                                                                                 
      - "Overall/Administer:tomlankhorst"                                                                                                                                                                          
      - "Overall/Read:authenticated"
```

However, after applying this config, (1) not `Project-based Matrix Authorization Strategy` but `Matrix-based security` is selected and (2) the permissions of `anonymous` are not applied. 

### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] 2.222.1  Jenkins version

- [x] 1.38 Plugin version

- [x] Official Jenkins Docker Image (lts-slim) in Ubuntu Bionic OS

<!--
Put an `x` into the [ ] to show you have filled the information below
Describe your issue below
-->
