### ISSUE TITLE
What is the best way to work with Jenkins credentials using CASC?

### ISSUE THREAD

**Issue by AlexPykavy** [jenkinsci/configuration-as-code-plugin#1348]
Hello,

We use this plugin to create initial Jenkins configuration (setup global variables, configuration, even jobs etc). See:

```
credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "Some password"
          id: "SomePassword"
          scope: GLOBAL
          secret: "SomePlainTextPassword"
```

In order to bypass it we can use a trick and use environment variable as the value. See:
```
credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "Some password"
          id: "SomePassword"
          scope: GLOBAL
          secret: "${SomeEnvVarPassword:-SomePlainTextPassword}"
```
It will set secret value as ${SomeEnvVarPassword} if it's defined and 'SomePlainTextPassword' otherwise.

Seems OK, but we install Jenkins as Docker container with some restart policy and CASC resets all configuration to default at restart. It means that if credentials will not be set as global environment variables then all credentials values will be reset to their default values: 'SomePlainTextPassword' in our case.

Does anybody think about the same problem? Or is it better option to work with Jenkins and CASC plugin to handle credentials?

If somebody already asked this question but I haven't noticed it, please feel free to close my one and redirect there.

Thanks in advance.
