### ISSUE TITLE
LDAP Strategy Configurator

### ISSUE THREAD

**Issue by sgnl19** [jenkinsci/configuration-as-code-plugin#138]
We are using the Configuration-as-Code Plugin together with the LDAPConfiguration from the LDAP Plugin.
LDAPConfiguration by default uses the FromGroupSearchLDAPGroupMembershipStrategy as GroupMembershipStrategy. We need to set the FromUserRecordLDAPGroupMembershipStrategy. There's a setter method "setGroupMembershipStrategy" annottated with the DataBoundSetter annotation. How can we achive that the setter method is called injecting the desired strategy?

**Comment by ndeloof** [comment]
`FromUserRecordLDAPGroupMembershipStrategy`'s Descriptor has no symbol, so you can use plain class name : "FromUserRecordLDAPGroupMembershipStrategy". As `LDAPGroupMembershipStrategy` is not declared an ExtensionPoint we can't guess a short name for it. I will prepare a pull-request for this purpose.

Doesn't the generated documentation give you a list of available values for this attribute ?


```yaml
ldap:
      configurations:
        - server: ldap.acme.com
          rootDN: dc=acme,dc=fr
          managerPasswordSecret: ${LDAP_PASSWORD}
          groupMembershipStrategy: FromUserRecordLDAPGroupMembershipStrategy

```
