### ISSUE TITLE
Support minimumNoInstancesActiveTimeRangeDays (ec2-plugin)

### ISSUE THREAD

**Issue by lifeofguenter** [jenkinsci/configuration-as-code-plugin#1389]
This does not seem to be supported: https://github.com/jenkinsci/ec2-plugin/blob/da14631cc9406d8d5dae5dd25ecfe5d642b86679/src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly#L142-L159

I tried:

```yaml
            minimumNumberOfInstances: 0
            minimumNumberOfInstancesTimeRangeConfig:
              minimumNoInstancesActiveTimeRangeFrom: 06:00
              minimumNoInstancesActiveTimeRangeTo: 15:00
              minimumNoInstancesActiveTimeRangeDays:
                monday: true
                tuesday: true
                wednesday: true
                thursday: true
                friday: true
                saturday: false
                sunday: false
            minimumNumberOfSpareInstances: 1
```

but get the following error:

```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class hudson.plugins.ec2.util.MinimumNumberOfInstancesTimeRangeConfig : minimumNoInstancesActiveTimeRangeDays.
```
