### ISSUE TITLE
Support for Warnings Plugin

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#140]
I verified support for Warnings plugin and it is not support out of the box
no DataBoundSetters
`warnings` element is exposed but can't find `parsers` that would be the attribute 

here is the configuration I expect should work:
```
jenkins:
  warnings:
    parsers:
      - name: "dummy parser"
        linkName: "whatever"
        trendName: "trend"
        regexp: "lkmlkjm"
        script: "here is a place for script"
        example: "and here for example message"
```

but I get 

```
java.lang.IllegalArgumentException: Invalid configuration elements for type class hudson.plugins.warnings.WarningsDescriptor : parsers
```
We may need to issue PR with fix to Warnings Plugin
