### ISSUE TITLE
Jenkins LDAP integration with ConfigMap is not working.

### ISSUE THREAD

**Issue by bishnuroy** [jenkinsci/configuration-as-code-plugin#1445]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Jenkins version - jenkins/jenkins:lts 

- [ ] Plugin version mentioned in Yaml

### Description

We have deployed JenkinsOperator and Agent Jenkins.
We are able to login jenkins with  jenkins-jperator local user.
But ldap integration with ConfigMap not working.
Looking for some help over here.
 

**OperetorYaml:**
```
---
# Source: crds/jenkins-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jenkins.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: Jenkins
    listKind: JenkinsList
    plural: jenkins
    singular: jenkins
  scope: Namespaced
  versions:
    - name : v1alpha2
      served: true
      storage: true
    - name : v1alpha1
      served: true
      storage: false

---
```
```
---
# Source: jenkins-operator/templates/operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-operator
  labels:
    app.kubernetes.io/name: jenkins-operator
    helm.sh/chart: jenkins-operator-0.3.4
    app.kubernetes.io/instance: jenkins-operator
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins-operator
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins-operator
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: jenkins-operator
      containers:
        - name: jenkins-operator
          image: virtuslab/jenkins-operator:v0.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          command:
            - jenkins-operator
          args: []
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jenkins-operator"
          resources:
            {}
```
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: jenkins-operator
  name: jenkins-operator-metrics
spec:
  ports:
  - name: http-metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  - name: cr-metrics
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    name: jenkins-operator
  type: ClusterIP
```

**JenkinsMaster:**

```
---
# Source: jenkins-operator/templates/jenkins.yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins-testjk01
spec:
  selector:
    name: jenkins-operator
  configurationAsCode:
    configurations:
    - name: jenkins-testjk01-ldap
    #secret: jenkins-operator-credentials-jenkins-testjk01
  groovyScripts:
    configurations:
    #secret:
      #name: jenkins-testjk01
  backup:
    containerName: backup
    action:
      exec:
        command: 
        - /home/user/bin/backup.sh
    interval: 30
    makeBackupBeforePodDeletion: true
  restore:
    containerName: backup
    action:
      exec:
        command: 
        - /home/user/bin/restore.sh
  master:
    basePlugins: 
    - name: kubernetes
      version: 1.25.2
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: 4.2.2
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.38"
    - name: kubernetes-credentials-provider
      version: "0.13"
    - name: ldap
      version: "1.24"
    - name: blueocean
      version: "1.23.0"
    - name: pipeline-build-step
      version: "2.12"
    - name: pipeline-github
      version: "2.5"
    - name: config-file-provider
      version: "3.6.3"
    - name: jdk-tool
      version: "1.4"
    - name: login-theme
      version: "1.1"
    - name: matrix-auth 
      version: "2.5"
    - name: monitoring
      version: "1.82.0"
    - name: kubernetes-client-api 
      version: "4.9.1-1" 
    - name: kubernetes-credentials
      version: "0.6.2"
    JCasC:
      enabled: true
      defaultConfig: true
    priorityClassName: 
    disableCSRFProtection: false
    containers:
      - name:  jenkins-master
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: 
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: 1
            memory: 500Mi
      - name: backup
        image: virtuslab/jenkins-operator-backup-pvc:v0.0.8
        imagePullPolicy: IfNotPresent
        env:
        - name: BACKUP_DIR
          value: /backup
        - name: JENKINS_HOME
          value: /jenkins-home
        - name: BACKUP_COUNT
          value: "3"
        volumeMounts:
        - mountPath: /jenkins-home
          name: jenkins-home
        - mountPath: /backup
          name: backup
    volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: jenkins-backup-testjk01
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
---

```
LDAPConfigMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-testjk01-ldap
data:
  jenkins-ldap-cm.yaml: |
    jenkins:
      systemMessage: "LDAP configured"
      securityRealm:
        ldap:
          configurations:
            - server: "ldap://test01.example.com"
              groupMembershipStrategy: 
                fromGroupSearch:
                   cn: "analytics_test"
              rootDN: ""
              userSearchBase: "ou=People"
              userSearch: "uid={0}"
              groupSearchBase: "ou=Group"
              groupSearchFilter: "objectClass=posixGroup"
              managerDN: "cn=Operator,ou=example,o=com"
              managerPasswordSecret: "********"
              displayNameAttributeName: "cn"
              mailAddressAttributeName: "mail"
              ignoreIfUnavailable: "true"

```
