### ISSUE TITLE
Obsolete configuration monitor UI broken

### ISSUE THREAD

**Issue by timja** [jenkinsci/configuration-as-code-plugin#1448]
![image](https://user-images.githubusercontent.com/21194782/90227916-43b38100-de0d-11ea-9530-39e9667aeee2.png)

### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version
2.252
- [x] Plugin version
1.43
- [x] OS
debian

### Description

Code is here:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/resources/io/jenkins/plugins/casc/ObsoleteConfigurationMonitor/message.jelly

Config that triggers the monitor:

```
  timestamperConfig:
    allPipelines: true
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
```
