### ISSUE TITLE
Unclassified root element is not compliant to YAML 1.2

### ISSUE THREAD

**Issue by Adiqq** [jenkinsci/configuration-as-code-plugin#1450]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version 2.235.1

- [x] Plugin version 1.41

- [x] OS Linux

### Description

YAML 1.2 specification tells us that keys must be unique. This leads to problem with parsers like go-yaml.v3 , which enforce duplicate key checks according to specification. Currently YAML document used by JCasC plugin might be not compliant, please see example below, where we have duplicate mapping keys.

https://yaml.org/spec/1.2/spec.html

> JSON's RFC4627 requires that mappings keys merely “SHOULD” be unique, while YAML insists they “MUST” be. Technically, YAML therefore complies with the JSON spec, choosing to treat duplicates as an error. In practice, since JSON is silent on the semantics of such duplicates, the only portable JSON files are those with unique keys, which are therefore valid YAML files.

```yaml
credentials:
    system:
      domainCredentials:
      - credentials:
      ...
    unclassified:          
      # artifactorybuilder plugin config, to access artifactory        
      artifactoryBuilder:
    ...
    unclassified:
      bitbucketEndpointConfiguration:
    ...
```

**Comment by timja** [comment]
I don't understand what you mean?

that's an invalid config file you've posted?

**Comment by Adiqq** [comment]
@timja It's valid from plugin perspective, however it's not compliant to YAML 1.2 specs. This is fine as long as you plan to edit config by hand, however in our case we would like to process them from code and that's where issue occurs.

In this example, issue is with duplicate "unclassified" key. This could be grouped as single "unclassified" key with list items, to avoid duplicate key, e.g. 

```yaml
credentials:
    system:
      domainCredentials:
      - credentials:
      ...
    unclassified:                 
      - artifactoryBuilder:
        ...
      - bitbucketEndpointConfiguration:
        ...
    ...
```
