### ISSUE TITLE
Possible to base64 encode secret into secretBytes for file type credentials?

### ISSUE THREAD

**Issue by hybmg57** [jenkinsci/configuration-as-code-plugin#1454]
#335 # Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [x] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [x] Jenkins version
- [x] Plugin version
- [x] OS
- [x] Reproduction steps

### Description

Jenkins 2.235.2

I am loading file using [`secrets.properties` file](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#using-properties-file) like below:

```
- file:
  description: "Password file"
  fileName: "PASSWORD_TEXT"
  id: "PASSWORD_TEXT"
  scope: GLOBAL
  secretBytes: "${base64:${PASSWORD_TEXT}}"
```

however this seems to output empty value.

Is there a way to not use `readFile:` and just use `base64` with secret text variable?
