### ISSUE TITLE
Update kubernetes-helm demo

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/configuration-as-code-plugin#1455]
### Feature Request

I suggest to update the kubernetes-helm demo to use the chart from the new location.

> Now grab a copy of the helm chart values file and adjust the Master part a little bit

I often see people doing this. I recommend instead to create a `values.yaml`, which just contains the changes which you want to do.

Otherwise as in the example you might miss to update values which have been changed in the chart and wonder why things stop working.

```
master:
  sidecars:
    configAutoReload:
      image: shadwell/k8s-sidecar:0.0.2
```

is now defined as 

```
master:
  sidecars:
    configAutoReload:
      image: kiwigrid/k8s-sidecar:0.1.144
```

So you might even benefit from updates if you omit values.

`installPlugins` of the chart will ensure that `kubernetes` and `configuration-as-code` plugins are installed. If you need additional plugins for the demo those can be specified via `additionalPlugins`.
