### ISSUE TITLE
User database option setting gets reverted

### ISSUE THREAD

**Issue by arunsr2015** [jenkinsci/configuration-as-code-plugin#1460]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ x] Jenkins version

- [ x] Plugin version

- [ x] OS

### Description

Please describe your issue here.
I have recently installed a jenkins server Jenkins 2.235.5 on GKE .

I added this Jenkins’ own user database setting thru the global setting and had users sign up, however after somtime maybe 30mins the setting is lost and it reverts back to old setting which is none and only admin can login

i do see this in th epod logs
[2020-09-14 22:36:48] File in configmap jcasc-default-config.yaml ADDED
[2020-09-14 22:36:49] POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=jenkins-fedramp-55fd87df7f-cbx2q. Response: 200 OK
[2020-09-14 23:18:10] Working on configmap None/None
[2020-09-14 23:18:10] configmap does not have data.
[2020-09-14 23:18:10] Working on configmap jenkins/jenkins-fedramp-jenkins-jcasc-config
[2020-09-14 23:18:10] File in configmap jcasc-default-config.yaml ADDED
[2020-09-14 23:18:10] POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=jenkins-fedramp-55fd87df7f-cbx2q. Response: 200 OK
2020-09-14 22:45:49.638+0000 [id=16]	INFO	o.c.j.p.k.KubernetesClientProvider$SaveableListenerImpl#onChange: Invalidating Kubernetes client: kubernetes null
2020-09-14 23:10:39.301+0000 [id=2171]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Periodic background build discarder
2020-09-14 23:10:39.302+0000 [id=2171]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Periodic background build discarder. 1 ms
2020-09-14 23:18:10.086+0000 [id=13]	INFO	i.j.p.casc.TokenReloadAction#doIndex: Configuration reload triggered via token
2020-09-14 23:18:10.103+0000 [id=13]	WARNING	i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class org.csanchez.jenkins.plugins.kubernetes.PodTemplate#listener: type is abstract but not Describable.
2020-09-14 23:18:10.403+0000 [id=13]	WARNING	i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class org.csanchez.jenkins.plugins.kubernetes.PodTemplate#listener: type is abstract but not Describable.

Not sure what is happening

looks like setting is overwritten by configmap

**Comment by timja** [comment]
Did you change it through the UI?

Which helm chart version?

The helm chart also sets a security realm so might revert it

Cc @torstenwalter who is more familiar with this

**Comment by torstenwalter** [comment]
Did you configure user database via JCasC or via the UI?

My guess is that you did it via UI and it got overwritten when JCasC settings have been reloaded. You can reproduce it by adding one user via the UI and then go to configuration as code plugin and click reload.

You should configure it via JCasC or disable this setting explicitly.

**Comment by torstenwalter** [comment]
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/_helpers.tpl#L74-L84 contains the default configuration

**Comment by arunsr2015** [comment]
Thank for the reply.
This is the default 
 # enables configuration done directly via XML files
  enableXmlConfig: false
  # Allows to configure different SecurityRealm using Jenkins XML
  securityRealm: |-
    <securityRealm class="hudson.security.LegacySecurityRealm"/>

What would i need to change in the values.yaml to persist the user Jenkins’ own user database setting.
@torstenwalter  yes so far been doing that sertting via the GUI.

**Comment by torstenwalter** [comment]
In the snippet I shared above you can check which values are used.

**Comment by arunsr2015** [comment]
@torstenwalter I see that the default values are for the , Delegate to servlet container	. I may not be understanding correct. Bit confused how to change it in the values yaml

D i need to provide a config file JCasC or should i disable it

**Comment by arunsr2015** [comment]
Also i did a change in ui and then did a view of the config

```
securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "xxx"
        name: "Arun k Srinivasan"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "xxxx"
```
I guess i need to set it to local in the values.yaml

**Comment by arunsr2015** [comment]
I think i get it now, i have added following to the values.yaml
 ```
JCasC:
    enabled: true
    defaultConfig: true
    configScripts: {}
    # Ignored if securityRealm is defined in master.JCasC.configScripts and
    # ignored if master.enableXmlConfig=true as master.securityRealm takes precedence
    securityRealm: |-
      local:
        allowsSignup: true
        enableCaptcha: false
```
and it persists

**Comment by torstenwalter** [comment]
@arunsr2015 Thank you for the feedback. Does it still create the admin user?

If yes then we could set these values by default.

**Comment by arunsr2015** [comment]
It doesnt create the admin in the local database, i had done the setting thru ui and signed up a user. Now i have picked the matrix stratergy

i had to add this in the values.yaml

```
securityRealm: |-
      local:
        allowsSignup: true
        enableCaptcha: false
    # Ignored if authorizationStrategy is defined in master.JCasC.configScripts and
    # ignored if master.enableXmlConfig=true as master.authorizationStrategy takes precedence
    authorizationStrategy: |-
      #loggedInUsersCanDoAnything:
        #allowAnonymousRead: false
      globalMatrix:
        permissions:
        - "Credentials/Update:authenticated"
        - "Job/Build:authenticated"
        - "Job/Cancel:authenticated"
        - "Job/Configure:authenticated"
        - "Job/Create:authenticated"
        - "Job/Discover:authenticated"
        - "Job/Move:authenticated"
        - "Job/Read:authenticated"
        - "Job/Workspace:authenticated"
        - "Overall/Administer:asrinivasan"
        - "Overall/Read:anonymous"
        - "Overall/Read:authenticated"
        - "Overall/SystemRead:authenticated"
```

Is this the right approach
