### ISSUE TITLE
Configuration not working when Jenkins machine is hosted in AWS

### ISSUE THREAD

**Issue by jmcduffie** [jenkinsci/configuration-as-code-plugin#1462]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version 2.254

- [x] Plugin version 1.36

- [x] CentOS Linux release 7.6.1810 (Core)

### Description

The following configuration does not parse correctly when running on a Jenkins machine hosted in AWS. It does, however, work on a Jenkins machine that is not hosted in AWS with other factors such as Jenkins and plugin version remaining the same.

```
jenkins:
  clouds:
  securityRealm:
    saml:
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
      displayNameAttributeName: "displayname"
      groupsAttributeName: "groups"
      maximumAuthenticationLifetime: 86400
      usernameAttributeName: "username"
      usernameCaseConversion: "none"
      logoutUrl: "corporate_url"
      idpMetadataConfiguration:
        period: 0
        xml : |
          <bunch of xml with corporate info>


undefined:
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
    - mojoVersion: "3.6.1.1688"
      name: "aws-prod-sonar"
      serverUrl: "corporate_url"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
    - mojoVersion: "3.6.1.1688"
      name: "aws-stage-sonar"
      serverUrl: "corporate_url"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
```
