### ISSUE TITLE
JCASC creating corrupted file credential from DSA private key

### ISSUE THREAD

**Issue by thorntonryan** [jenkinsci/configuration-as-code-plugin#1537]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version
2.269
- [x] Plugin version

Plugin | Version
-------|----------
JCasC | 1.46
Credentials |  2.3.14
Plain Credentials | 1.7

- [x] OS
Ubuntu

### Description

I'm using JCasC to inject DSA credentials as a secret file and I'm getting unusual behavior that seemingly results in a corrupted credential file.

I'm setting up the file credential by doing the following:
```yml
credentials:
  system:
    domainCredentials:
    - credentials:
      - file:
          description: "DSA private key"
          fileName: "dsa_priv.pem"
          id: "dsa_priv"
          scope: GLOBAL
          secretBytes: "${base64:${file}}"
```
And by placing my credential at `/run/secrets/file` in order to load it via the [docker secrets](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#docker-secrets) mechanism and then applying my configuration.

But JCasC doesn't appear to be generating the same credential that would be created if I went through the Jenkins GUI and manually added a secret file to the credential store.

I noticed this because the script I'm running that attempts to read the JCasC created credential bombs because it can't correctly deserialize it. But it works just fine on a file credential created from the GUI with the same contents.

But it's also pretty easy to observe the difference in behavior with a simple pipeline script on a test key:

```yml
pipeline {
    agent any

    stages {
        stage('test') {
            environment {
                 dsa_priv= credentials('dsa_priv')
             }
            steps {
                script {
                    def contents = readFile file: env.dsa_priv
                    echo contents
                }
            }
        }
    }
}
```

When I attempt to read the credential loaded via the Jenkins GUI using the above pipeline, I get something that looks like:
```
-----BEGIN DSA PRIVATE KEY-----
...
-----END DSA PRIVATE KEY-----
```
But when I do same on the JCasC generated file credential, I get a bunch of mojibake:
```
���b
...
���b
```
Playing around some, if I swap the file contents for something like:
```
asdfsdf---
hello world
--asdfasdf
```
JCasC correctly creates the credential and dumps the contents:
```
[Pipeline] echo
asdfsdf---
hello world
--asdfasdf
```
But the moment I add a leading - to the file:
```
-asdfsdf---
hello world
--asdfasdf
```
Something goes wrong and I get nothing:
```
[Pipeline] echo

```

I'm not quite sure if the problem is with my usage, JCasC, or one of its dependent plugins (`credentials`, `plain-credentials`, etc.).

_Thanks for all the work maintaining this great plugin and for taking the time to read my bug report!_

**Comment by jetersen** [comment]
File has to be UTF8 encoded.

**Comment by thorntonryan** [comment]
One potential workaround, which seems conceptually wrong, but further illustrates the problem.

If instead of a `file` credential I use a `basicSSHUserPrivateKey`, it works:

```
credentials:
  system:
    domainCredentials:
    - credentials:
      - file:
          description: "DSA private key"
          fileName: "dsa_priv.pem"
          id: "dsa_priv"
          scope: GLOBAL
          secretBytes: "${base64:${file}}"
      - basicSSHUserPrivateKey:
          description: "workaround"
          id: "dsa_priv_workaround"
          privateKeySource:
            directEntry:
              privateKey: "${base64:${file}}"
          scope: GLOBAL
          username: "unused"
```

```yml
pipeline {
    agent any

    stages {
        stage('test') {
            environment {
                 dsa_priv= credentials('dsa_priv')
                 dsa_priv_workaround= credentials('dsa_priv_workaround')
             }
            steps {
                script {
                    def contents = readFile file: env.dsa_priv
                    echo contents

                    def workaround= readFile file: env.dsa_priv_workaround
                    echo workaround
                }
            }
        }
    }
}
```

I get:

```
[Pipeline] echo
file
[Pipeline] readFile
[Pipeline] echo
��A�44�=1
...
�baDOލL�_�zO���@�%���:�n7[Կ�+Q���vAP)�d�Q���������H�!P���
[Pipeline] echo
basicSSHUserPrivateKey
[Pipeline] readFile
[Pipeline] echo
----BEGIN DSA PRIVATE KEY-----
...
-----END DSA PRIVATE KEY-----

```

**Comment by thorntonryan** [comment]
> File has to be UTF8 encoded.

The file is already UTF8 encoded:

**Comment by jetersen** [comment]
Not sure what to say, test is passing: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/src/test/java/io/jenkins/plugins/casc/CredentialsReadmeTest.java 🙈

**Comment by thorntonryan** [comment]
For reference, I created my RSA private key by doing:
```sh
openssl dsaparam 4096 > dsaparam.pem
openssl gendsa -out dsa_priv.pem dsaparam.pem
```

**Comment by thorntonryan** [comment]
> Not sure what to say, test is passing: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/src/test/java/io/jenkins/plugins/casc/CredentialsReadmeTest.java 🙈

Which test is testing a secret `file` credential with an RSA private key?

**Comment by jetersen** [comment]
not sure how your passing in the `file` attribute but it my be the source of messing with the input.

Could you try using `${readFileBase64:myFilePath}`

**Comment by jetersen** [comment]
The file implementation is tested here: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/src/test/java/io/jenkins/plugins/casc/CredentialsReadmeTest.java#L134-L140

**Comment by thorntonryan** [comment]
>not sure how your passing in the file attribute but it my be the source of messing with the input.

I'm using the [docker secrets](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#docker-secrets) mechanism to load my file.

The contents of `/run/secrets/file` are my private key.

**Comment by thorntonryan** [comment]
> The file implementation is tested here: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/src/test/java/io/jenkins/plugins/casc/CredentialsReadmeTest.java#L134-L140

But that test isn't using a ["PRIVATE_KEY"](https://github.com/jenkinsci/configuration-as-code-plugin/blob/d4f41e1b31a2e33c74fa018523ac9c7a5e5bf6b5/integrations/src/test/java/io/jenkins/plugins/casc/CredentialsReadmeTest.java#L44-L58).

I'm not sure how to modify the test to test for the RSA key instead of [MY_SECRET_FILE](https://github.com/jenkinsci/configuration-as-code-plugin/blob/d4f41e1b31a2e33c74fa018523ac9c7a5e5bf6b5/integrations/src/test/java/io/jenkins/plugins/casc/CredentialsReadmeTest.java#L63), but my hunch is that if you did, it would fail for the same reasons I'm seeing.

**Comment by thorntonryan** [comment]
> Could you try using `${readFileBase64:myFilePath}`

OK weird. Cutting out the [docker secrets](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#docker-secrets) totally worked.

```
credentials:
  system:
    domainCredentials:
    - credentials:
      - file:
          description: "DSA private key"
          fileName: "dsa_priv.pem"
          id: "dsa_priv"
          scope: GLOBAL
          secretBytes: "${readFileBase64:/run/secrets/file}"
```
