### ISSUE TITLE
support "exclude" or regex patterns in "assignments" in authorizationStrategy

### ISSUE THREAD

**Issue by mortymacs** [jenkinsci/configuration-as-code-plugin#1541]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

When Jenkins has been deployed with its user management database, in In role-strategy-plugin we can only have `assignments` for users and only `anonymous` and `authenticated` groups. So, the limitation here is first we can't create a new group due to the Jenkins limitations and when we want to give permission to all users except one or several users, then we have to define the list of all users in the `assignments` field.

In our requirements, we look for having an `excludes` field for users who have to have limited access to specific projects. It would be applicable if instead of the `exclude` field, we support regex/pattern in `assignments`.

**Comment by jetersen** [comment]
use single quotes to avoid escaping and the regex should be correctly passed a string which Jenkins should convert to a regex pattern?

Also this is a feature request for the role-strategy-pluigin.

**Comment by mortymacs** [comment]
> use single quotes to avoid escaping and the regex should be correctly passed a string which Jenkins should convert to a regex pattern?
> 
> Also this is a feature request for the role-strategy-pluigin.

You mean it works for `assignments` field?

```
jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - '^(?!test-user$).*$'
```
