### ISSUE TITLE
Artifactory breaking change in version 3.11.0

### ISSUE THREAD

**Issue by ls-julien-deruere** [jenkinsci/configuration-as-code-plugin#1607]
[jenkins-jira]: https://issues.jenkins-ci.org
[dashboard]: https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=18341
[contributing]: ../blob/master/docs/CONTRIBUTING.md
[compatibility]: ../blob/master/docs/COMPATIBILITY.md

### Your checklist for this issue

🚨 Please review the [guidelines for contributing][contributing] to this repository.
💡 To better understand plugin compatibility issues, you can [read more here][compatibility]

- [x] Create an issue on [issues.jenkins-ci.org][jenkins-jira], set the component to the plugin you are reporting it against

- [x] Before creating an issue on [Jenkins JIRA][jenkins-jira], check for [an existing one via dashboard][dashboard]

- [ ] Link to [Jenkins JIRA issue][jenkins-jira]

- [ ] Ensure [Jenkins JIRA issue][jenkins-jira] has the label `jcasc-compatibility`

- [x] Link to plugin's GitHub repository

### Description

Breaking change here: https://github.com/jenkinsci/artifactory-plugin/commit/03a71a610650163abff1b18f100ff28e6f29aab1

The new jcasc configuration for artifactory is now:

```yaml
unclassified:
  artifactorybuilder:
    useCredentialsPlugin: true
    jfrogInstances:
      - instanceId: artifactory
        url: http://acme.com/artifactory
        deployerCredentialsConfig:
          credentialsId: "artifactory"
        resolverCredentialsConfig:
          username: artifactory_user
          password: "${ARTIFACTORY_PASSWORD}"
```
