### ISSUE TITLE
'unclassified' section is missing in casc_configs

### ISSUE THREAD

**Issue by irom77** [jenkinsci/configuration-as-code-plugin#1611]
- [x ] Jenkins version
2.277.4 (helm chart jenkins-3.3.9)

- [x ] Plugin version
1.51
- [ x] OS
k8s v1.18.14 

### Description

I use the helm values below 
```
JCasC:
    unclassified:      
      mailer:
        replyToAddress: do-not-reply@corp.com
        smtpHost: relay.corp.com
        smtpPort: 25
      location:
        adminAddress: "do-not-reply@corp.com"
```

but after upgrade and restart /var/jenkins_home/casc_configs shows 'unclassified' section empty. I can update some other sections (i.e. securityRealm) without any issues 

```
>kubectl -n jenkins exec -it jenkins-0 -c jenkins -- bash -c "cat /var/jenkins_home/casc_configs/jcasc-default-config.yaml"
...
unclassified:
  location:
    adminAddress:
    url: http://ops-jenkins:8080

```
