### ISSUE TITLE
Reading docker secret from file includes newline

### ISSUE THREAD

**Issue by MadsNielsen** [jenkinsci/configuration-as-code-plugin#163]
When reading from docker-secrets we read newlines as well. Example here is a file with the secret: secr3t
```
// https://mvnrepository.com/artifact/commons-io/commons-io
@Grapes(
    @Grab(group='commons-io', module='commons-io', version='2.5')
)

import org.apache.commons.io.FileUtils

final File file = new File("/var/deploy/secrets/adminpw")
String result = "'${FileUtils.readFileToString(file)}'"
```
``` 
groovy> // https://mvnrepository.com/artifact/commons-io/commons-io 
groovy> @Grapes( 
groovy>     @Grab(group='commons-io', module='commons-io', version='2.5') 
groovy> ) 
groovy> import org.apache.commons.io.FileUtils 
groovy> final File file = new File("/var/deploy/secrets/adminpw") 
groovy> String result = "'${FileUtils.readFileToString(file)}'" 
 
Result: 'secr3t
'
```

**Comment by buep** [comment]
Related to commit https://github.com/jenkinsci/configuration-as-code-plugin/commit/c83470c3b842358bbbbbb3f6af996dfa278953af

and our issues with reading the password in our demo setup: https://github.com/Praqma/praqma-jenkins-casc/issues/1

**Comment by MadsNielsen** [comment]
Turns out im an idiot. The reason i raised this issue is that when i created the secrets with `echo secr3t > /var/deploy/secrets/adminpw` i didn't notice that the file actually has a newline. 

You can manually edit out the newline from a proper editor and it works.

**Comment by buep** [comment]
Well I don't think you will be the only one overlooking the issue... if you look at our comment in https://github.com/Praqma/praqma-jenkins-casc/issues/1 we even did not fully understand that `$` sign outputted from `CAT -A` command really is a newline.

I think other will face the same issue possible, so maybe we should write a warning if we see newline in the end of the input? 
White-space issues are really hard to debug often for users.

**Comment by buep** [comment]
@ewelinawilkosz  @ndeloof what do you think? I'm not sure if you get the full context here, you might need to read up on the linked commits and issues.

But if the user add a newline to the file the password is wrong. Obviously, but it might be a problem several users face as some editor do it and not all of them shows it.

The `.trim()` is obviously not good I think.

Anyway not high priority, just some user feedback @MadsNielsen experienced himself.

**Comment by ndeloof** [comment]
@MadsNielsen did you experienced this issue with actual docker-secrets or a file you created by yourself ?

**Comment by MadsNielsen** [comment]
@ndeloof I did use docker secrets. With docker-compose though so not through docker swarm. 

I.E like so: 

``` 
version: '3.3'

services:
  jenkins: 
    build: 
      context: ./master
      args:
        JAVA_OPTS: '-Djenkins.CLI.disabled=true'
    ports: 
      - 80:8080
      - 50000:5000
    volumes:
      - jenkins_home:/var/jenkins_home
    secrets:
      - github
      - adminpw
secrets:
  github:
    file: /var/deploy/secrets/github
  adminpw:
    file: /var/deploy/secrets/adminpw
volumes:
  jenkins_home:
```
It's for our portable demo setup. But i think it might be an error 40 on my part.
