### ISSUE TITLE
JSON Schema incorrectly nests some fields

### ISSUE THREAD

**Issue by fatmcgav** [jenkinsci/configuration-as-code-plugin#1636]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version - `2.289.2`

- [x] Plugin version - `1.51`

- [x] OS - `Docker image`

### Description

I'm trying to use the JSON Schema to validate our JCasC configuration.

However it looks like the schema incorrectly nests a number of fields, such as `globalNodeProperties` and `nodeProperties`.

Working CasC config:
```yaml
jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disabledAdministrativeMonitors:
    - jenkins.security.s2m.MasterKillSwitchWarning
  disableRememberMe: false
  globalNodeProperties:
    - envVars:
        env:
          - key: JENKINS_CLUSTER_ID
            value: jenkins-ci
          - key: JENKINS_HOME
            value: /var/lib/jenkins
          - key: RUNBLD_DISABLE_NOTIFICATIONS
            value: true
  labelString: 'flyweight inspect'
  mode: EXCLUSIVE
  nodeProperties:
    - envVars:
        env:
          - key: JENKINS_HOME
            value: /var/jenkins_home
  numExecutors: 2
  projectNamingStrategy: "standard"
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 4
```

Validation python script: https://gist.github.com/fatmcgav/2d3ae1a1ab9fade6c344a40e13901461#file-jcasc-validate-py

Error encountered:
```
python3 jcasc-validate.py -i base.yaml --schema-url jcasc-schema.json
jcasc-validate.py:19: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  jsonschema.validate(yaml.load(fobj), schema)
Additional properties are not allowed ('globalNodeProperties', 'nodeProperties' were unexpected)
```

Those properties _are_ defined in the downloaded schema, but they're nested under an additional `jenkins` key... So rather than being `jenkins.globalNodeProperties`, they're `jenkins.jenkins.globalNodeProperties`...

Any ideas?
