### ISSUE TITLE
Spurious warning about `GitSCMSource.owner`

### ISSUE THREAD

**Issue by jglick** [jenkinsci/configuration-as-code-plugin#1637]
Linux (Docker), Jenkins 2.289.1, plugin version 1.51. Given YAML like

```yaml
unclassified:
  globalLibraries:
    libraries:
    - defaultVersion: main
      name: xxx
      implicit: true
      retriever:
        modernSCM:
          scm:
            git:
              remote: https://github.com/yyy/zzz
```

I received a warning (2×)

```
WARNING	i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.plugins.git.GitSCMSource#owner: type is abstract but not Describable.
```

I presume that refers to https://github.com/jenkinsci/scm-api-plugin/blob/14f2b9da3554d1ac3c43da5f4f39c5d8fdfe7edc/src/main/java/jenkins/scm/api/SCMSource.java#L224-L248 but this is just a backreference field which should never be touched by JCasC. (And in the case of library definitions, it is meaningless and unused.)
