### ISSUE TITLE
Unable to login to Jenkins after Jenkins upgrade to 2.289.2

### ISSUE THREAD

**Issue by srikanthareddy** [jenkinsci/configuration-as-code-plugin#1638]
HI,

After upgrading the Jenkins version to 2.289.2, the jenkins is not working as it throws the below error 

java.lang.IllegalArgumentException: Permission can not be null for sid:{USER ID}

There was no changes to the Permission Matrix

**Comment by Sickafant** [comment]
Only started noticing this now as well, since things load fine if I have an existing volume in place with config loaded. But when spinning up from a fresh state the error is seen:


```
jenkins                | 2021-08-31 18:21:50.292+0000 [id=23]	SEVERE	hudson.util.BootFailure#publish: Failed to initialize Jenkins
jenkins                | java.lang.IllegalArgumentException: Permission can not be null for sid:authenticated
jenkins                | 	at hudson.security.GlobalMatrixAuthorizationStrategy.add(GlobalMatrixAuthorizationStrategy.java:95)
jenkins                | 	at org.jenkinsci.plugins.matrixauth.integrations.casc.MatrixAuthorizationStrategyConfigurator.lambda$setPermissions$3(MatrixAuthorizationStrategyConfigurator.java:65)
jenkins                | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
jenkins                | 	at org.jenkinsci.plugins.matrixauth.integrations.casc.MatrixAuthorizationStrategyConfigurator.setPermissions(MatrixAuthorizationStrategyConfigurator.java:62)
jenkins                | 	at io.jenkins.plugins.casc.Attribute.setValue(Attribute.java:231)
jenkins                | 	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:357)
jenkins                | Caused: io.jenkins.plugins.casc.ConfiguratorException: string: Failed to set attribute permissions(class: class java.lang.String, multiple: true)
jenkins                | 	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:359)
jenkins                | 	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:276)
jenkins                | 	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$doConfigure$16668e2$1(HeteroDescribableConfigurator.java:277)
jenkins                | 	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
```

Will raise an issue against the matrix auth plugin.

**Comment by jetersen** [comment]
With a example or snippet of your config, we cannot reproduce.

**Comment by Sickafant** [comment]
Just tried to pare things down to a minimal config and have some new findings:

Fails with this.
```
jenkins:
  securityRealm:
    local:
     allowsSignup: true

  authorizationStrategy:
    projectMatrix:
      permissions:
        #- "Overall/Administer:authenticated"
        - "View/Read:authenticated"

unclassified:
  location:
    url: "http://localhost:8080"
```

But when having authenticated as an admin first, it passes:
```
jenkins:
  securityRealm:
    local:
     allowsSignup: true

  authorizationStrategy:
    projectMatrix:
      permissions:
        - "Overall/Administer:authenticated"
        - "View/Read:authenticated"

unclassified:
  location:
    url: "http://localhost:8080"
```
After that, subsequent loads and changes work, even when removing admin for authenticated sid.

plugins.txt:
```
configuration-as-code:1.52
matrix-auth:2.6.8
saml:2.0.8
```>
total plugins:
```

All requested plugins:

Plugins that will be downloaded:

Resulting plugin list:
apache-httpcomponents-client-4-api 4.5.13-1.0
bouncycastle-api 2.24
caffeine-api 2.9.2-29.v717aac953ff3
configuration-as-code 1.52
display-url-api 2.3.5
mailer 1.34
matrix-auth 2.6.8
saml 2.0.8
snakeyaml-api 1.29.1
Done
```
