### ISSUE TITLE
 basicSSHUserPrivateKey creates file with missing leading `-` character

### ISSUE THREAD

**Issue by dustymabe** [jenkinsci/configuration-as-code-plugin#1646]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version

2.277.3

- [x] Plugin version 

1.51

- [x] OS

RHEL 8.4

### Description

I'm having an issue where the `basicSSHUserPrivateKey` credentials is creating a file with a missing leading `-` character.

The original file in has a first line that looks like:

```
-----BEGIN OPENSSH PRIVATE KEY-----
```

The file created (via `withCredentials()`) only has four dashes at the beginning:

```
----BEGIN OPENSSH PRIVATE KEY-----
```

The original definition looks like:

```
credentials:          
  system:             
    domainCredentials:
      - credentials:  
        - basicSSHUserPrivateKey:                                       
            scope: GLOBAL                                               
            id: builder-sshkey-key                         
            username: builder                                           
            description: AARCH64 Builder SSH Key                   
            privateKeySource:                                           
              directEntry:                                              
                privateKey: "${readFile:${builder/sshkey}}"

```

It then gets picked up in a withCredentials call like:

```
withCredentials([                                                              
    sshUserPrivateKey(credentialsId: 'builder-sshkey-key',        
                      usernameVariable: 'REMOTEUSER',                          
                      keyFileVariable: 'CONTAINER_SSHKEY')                     
]) { }                                                                           
```

I've been able to workaround the issue by putting in the following workaround
inside a shell block:

```
sed -i s/^----BEGIN/-----BEGIN/ \$CONTAINER_SSHKEY                         
```

I notice a similar (missing beginning `-`) in the last few lines of the user report here: https://github.com/jenkinsci/configuration-as-code-plugin/issues/1537#issuecomment-740052170

Am I doing something wrong here?
