### ISSUE TITLE
File credentials demo is unclear about base64 encoding

### ISSUE THREAD

**Issue by neilhwatson** [jenkinsci/configuration-as-code-plugin#1654]
### Description

The demo document on credentials is not clear about file secrets (https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/credentials#example):

```
 - file:
              scope: GLOBAL
              id: "secret-file"
              fileName: "mysecretfile.txt"
              secretBytes: "${base64:${readFile:${SECRET_FILE_PATH}}}" # secretBytes requires base64 encoded content
```

Does this mean the target file must already be base64 encoded or that the base64 function on the left is encoding it?
