### ISSUE TITLE
remotingSecurity enabled is oppsite of what is intended.

### ISSUE THREAD

**Issue by casz** [jenkinsci/configuration-as-code-plugin#172]
This yaml disables Agent -> Master Access Control
```yaml
jenkins:
  remotingSecurity:
    enabled: true
```

while this yaml enables it.
```yaml
jenkins:
  remotingSecurity:
    enabled: false
```

![image](https://user-images.githubusercontent.com/1661688/39031954-ad995790-446b-11e8-8b72-598b00686c80.png)

@oleg-nenashev 

https://github.com/jenkinsci/configuration-as-code-plugin/pull/90#issuecomment-382980617
