### ISSUE TITLE
JCasC LDAP password not working

### ISSUE THREAD

**Issue by longc** [jenkinsci/configuration-as-code-plugin#1734]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version 2.304

- [x] Plugin version
        configuration-as-code:1.52
        ldap:2.7
- [x] OS alpine

### Description

I tried the LDAP configuration as code in https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/ldap, the LDAP password environment variable or from secret file never work, I can see a hash value for the managerPasswordSecret has been updated in Jenkins config.xml after restart, but jenkins throws out the exception error at login, it says the password is incorrect.
```
SEVERE o.s.s.w.a.AbstractAuthenticationProcessingFilter#doFilter: An internal error occurred while trying to authenticate the user. javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580]
```
The only way to get the ldap password working is to change the password via Jenkins Console, it generates new hash value in jenkins config.xml, then I can use the new hash value in JCasC.
```
managerPasswordSecret: {HASH_VALUE}
```

Here are the steps to re-produce the issue:

- Create ldap password secret in kubernetes
```
kubectl -n <jenkins_namespace> create secret generic ldap.password --from-literal=ldap.password='<ldap.password>'
```
- Create LDAP configuration file "casc_security.yaml"
```
jenkins:
  securityRealm:
    ldap:
      configurations:
        - server: example.com
          rootDN: DC=example,DC=com
          userSearch: "(&(objectCategory=User)(sAMAccountName={0}))"
          groupSearchFilter: "(&(objectClass=group))"
          groupMembershipStrategy:
            fromGroupSearch:
              filter: "(&(objectClass=group)(CN=GROUP_1))"
          managerDN: "manager"
          managerPasswordSecret: "${readFile:/secrets/ldap.password}"
          displayNameAttributeName: givenName
          mailAddressAttributeName: sn
      cache:
        size: 100
        ttl: 10
      userIdStrategy: CaseInsensitive
      groupIdStrategy: CaseSensitive
      disableMailAddressResolver: true
      disableRolePrefixing: true
```
- Install Jenkins with LDAP configuration
```
helm3 upgrade jenkins jenkins/jenkins \
    --install \
    --history-max 100 \
    --atomic \
    --wait \
    --timeout 5m \
    --namespace <jenkins_namespace> \
    --version 3.5.11 \
    --set persistence.size=10Gi \
    --set persistence.volumes[0].name="ldap-password",persistence.volumes[0].secret.secretName="ldap.password" \
    --set persistence.mounts[0].name="ldap-password",persistence.mounts[0].mountPath="/secrets" \
    --set controller.tag=2.304-alpine \
    --set controller.serviceType=ClusterIP \
    --set controller.JCasC.defaultConfig=false \
    --set-file controller.JCasC.configScripts.security="./casc_security.yaml"
```
