### ISSUE TITLE
SAML settings wiped out on config load

### ISSUE THREAD

**Issue by nimbuscrenel** [jenkinsci/configuration-as-code-plugin#1762]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version: 2.303.2

- [x] Plugin version: 1.54 

- [x] OS: Ubuntu 20.04

### Description

After configuring SAML settings and saving changes to my jcasc yaml file, the settings are wiped out and the following error is displayed when viewing the casc config via the GUI:

```
- samlCustomProperty:
    attributes: |-
      FAILED TO EXPORT
      org.jenkinsci.plugins.saml.user.SamlCustomProperty#attributes: No configurator found for type class org.jenkinsci.plugins.saml.user.SamlCustomProperty$Attribute
```

This is seen using the SAML 2.0.8 and 1.1.8 plugin versions.

config file for SAML in casc yaml looks like this:
```
securityRealm:
  saml:
    binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    displayNameAttributeName: "displayName"
    emailAttributeName: "Email"
    groupsAttributeName: "group"
    idpMetadataConfiguration:
      period: 0
      url: "https://xxxxxxxxx.okta.com/app/xxxxxxxxxxxxx/sso/saml/metadata"
    logoutUrl: "https://xxxxxxxxxx.okta.com"
    maximumAuthenticationLifetime: 31536000
    usernameCaseConversion: "none"
```
