### ISSUE TITLE
Include plugin own settings into the downloaded yaml

### ISSUE THREAD

**Issue by proski** [jenkinsci/configuration-as-code-plugin#1792]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

I'm using following section in the beginning of `jenkins.yaml`:

```
configuration-as-code:
  version: "1"
  deprecated: "warn"
  restricted: "warn"
  unknown: "warn"
```

However that section is not present in the downloaded `jenkins.yaml`. Please include it. Rationale:

- The settings become discoverable.
- Issues like #1581 won't be filed again.
- Users won't need to restore the missing section if they keep `jenkins.yaml` under version control.
- This plugin would do what it wants other plugins to do, i.e. save their settings.
