### ISSUE TITLE
Invalid configuration elements for type class jenkins.model.GlobalConfigurationCategory$Unclassified : globalLibraries,gitSCM,notifyBitbucket

### ISSUE THREAD

**Issue by njpau** [jenkinsci/configuration-as-code-plugin#1815]
This is the unclassified section of my casc config:
```
unclassified:
  ansiColorBuildWrapper:
    colorMaps:
    - black: "#000000"
      blackB: "#4C4C4C"
      blue: "#1E90FF"
      blueB: "#4682B4"
      cyan: "#00CDCD"
      cyanB: "#00FFFF"
      green: "#00CD00"
      greenB: "#00FF00"
      magenta: "#CD00CD"
      magentaB: "#FF00FF"
      name: "xterm"
      red: "#CD0000"
      redB: "#FF0000"
      white: "#E5E5E5"
      whiteB: "#FFFFFF"
      yellow: "#CDCD00"
      yellowB: "#FFFF00"
    - black: "#000000"
      blackB: "#555555"
      blue: "#0000AA"
      blueB: "#5555FF"
      cyan: "#00AAAA"
      cyanB: "#55FFFF"
      defaultBackground: 0
      defaultForeground: 7
      green: "#00AA00"
      greenB: "#55FF55"
      magenta: "#AA00AA"
      magentaB: "#FF55FF"
      name: "vga"
      red: "#AA0000"
      redB: "#FF5555"
      white: "#AAAAAA"
      whiteB: "#FFFFFF"
      yellow: "#AA5500"
      yellowB: "#FFFF55"
    - black: "black"
      blackB: "black"
      blue: "blue"
      blueB: "blue"
      cyan: "cyan"
      cyanB: "cyan"
      green: "green"
      greenB: "green"
      magenta: "magenta"
      magentaB: "magenta"
      name: "css"
      red: "red"
      redB: "red"
      white: "white"
      whiteB: "white"
      yellow: "yellow"
      yellowB: "yellow"
    - black: "#2E3436"
      blackB: "#2E3436"
      blue: "#3465A4"
      blueB: "#3465A4"
      cyan: "#06989A"
      cyanB: "#06989A"
      defaultBackground: 0
      defaultForeground: 7
      green: "#4E9A06"
      greenB: "#4E9A06"
      magenta: "#75507B"
      magentaB: "#75507B"
      name: "gnome-terminal"
      red: "#CC0000"
      redB: "#CC0000"
      white: "#D3D7CF"
      whiteB: "#D3D7CF"
      yellow: "#C4A000"
      yellowB: "#C4A000"
    globalColorMapName: "xterm"

  audit-trail:
    logBuildCause: true
    loggers:
    - logFile:
        count: 10
        limit: 50
        log: "/var/log/jenkins/audit-%g.log"
    pattern: ".*/(?:configSubmit|doDelete|postBuildResult|enable|disable|cancelQueue|stop|toggleLogKeep|doWipeOutWorkspace|createItem|createView|toggleOffline|cancelQuietDown|quietDown|restart|exit|safeExit)"

  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            artifactDaysToKeepStr: "14"
            artifactNumToKeepStr: "4"
  diskUsageProjectActionFactory:
    checkWorkspaceOnSlave: true
    historyLength: 183
    showGraph: true
    timeoutWorkspace: 5
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      address: "xxx@yyy.com"
      smtpHost: "mail.yyy.com"
      smtpPassword: "{asdasdjhaksjdhakjs}"

  gitSCM:
    createAccountBasedOnEmail: false
    globalConfigEmail: "xxx@yyy.com"
    globalConfigName: "xxx.admin"
    showEntireCommitSummaryInChanges: true
    useExistingAccountWithSameEmail: false
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED

  globalLibraries:
    libraries:
    - allowVersionOverride: false
      defaultVersion: "master"
      implicit: true
      name: "shared-lib-repo"
      retriever:
        modernSCM:
          scm:
            git:
              id: "5a1af6c6-934d-4ef5-b9ca-904f74602543"
              remote: "ssh://git@bitbucket.yyy.com:7999/myproject/shared-lib-repo.git"
              traits:
              - "gitBranchDiscovery"
              - "gitTagDiscovery"
  groovy:
    installations:
    - name: "groovy_3.0.6"
      properties:
      - installSource:
          installers:
          - groovyInstaller:
              id: "3.0.6"
  location:
    url: "https://xxx.yyy.com/"
    adminAddress: "xxx@yyy.com"
  lockableResourcesManager:
    declaredResources:
    - name: "ABC"
  mailer:
    smtpHost: "mail.yyy.com"
  metricsAccessKey:
    accessKeys:
    - canHealthCheck: true
      canMetrics: true
      canPing: true
      canThreadDump: true
      description: "Access Key for Metrics Plugin Servlet Access."
      key: "xyz"
      origins: "*"

  notifyBitbucket:
    considerUnstableAsSuccess: false
    disableInprogressNotification: false
    ignoreUnverifiedSsl: false
    includeBuildNumberInKey: false
    prependParentProjectKey: false

  pollSCM:
    pollingThreadCount: 10
  shell:
    shell: ""
    # Specifying this wrapper as default shell creates a sane default, but breaks sh steps
    # in docker containers (which don't have this script installed), so I decided to leave
    # the default shell empty and force users to be explicit about their shell requirements
    # by using shebangs.
    # shell: "/bin/bashlogin.sh"

  # See here for details on customizing this material theme:
  #   http://afonsof.com/jenkins-material-theme/
  simple-theme-plugin:
    elements:
    - cssUrl:
  # Use green theme on staging
  # Will get changed to blue when deployed to production
        url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-blue.css"
  timestamper:
    allPipelines: true
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
```

The error I get when reloading CasC is:
```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class jenkins.model.GlobalConfigurationCategory$Unclassified : globalLibraries,gitSCM,notifyBitbucket.
Available attributes : administrativeMonitorsConfiguration, ansiColorBuildWrapper, artifactManager, audit-trail, buildDiscarders, buildMonitorView, buildStepOperation, casCGlobalConfig, defaultFolderConfiguration, defaultView, diskUsageProjectActionFactory, email-ext, envVarsFilter, fingerprints, globalConfigFiles, globalConfigurationImpl, globalDefaultFlowDurabilityLevel, groovy, httpRequestGlobalConfig, jiraGlobalConfiguration, junitTestResultStorage, location, lockableResourcesManager, mailer, masterBuild, mattermostNotifier, mavenModuleSet, metricsAccessKey, myView, nodeProperties, plugin, pollSCM, projectNamingStrategy, prometheusConfiguration, quietPeriod, rebuildDescriptor, resourceRoot, scmRetryCount, shell, simple-theme-plugin, singleConditionalBuilder, subversionSCM, testResultsAnalyzerExtension, timestamper, upstream, usageStatistics, viewsTabBar, webhook
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:376)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:365)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:777)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:713)
Caused: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:719)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:777)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:762)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:638)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:307)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:299)
```

What's weird is that this was working fine last week, I had rebooted my machine multiple times last week for testing purposes and CasC reloaded fine every single time. However, I come in this monday and do a machine reboot and CasC blows up like shown above. And every subsequent reboot has produced the same result. 

I bring up my jenkins infrastructure with IaC using ansible and terraform, and this is the list of plugins we are installing on the controller:
```
jenkins_pipeline_library_plugins_present:
          - name: ace-editor
            version: "1.1"
          - name: authentication-tokens
            version: "1.4"
          - name: apache-httpcomponents-client-4-api
            version: "4.5.13-1.0"
          - name: bootstrap4-api
            version: "4.6.0-3"
          - name: bouncycastle-api
            version: "2.20"
          - name: branch-api
            version: "2.6.4"
          - name: caffeine-api
            version: "2.9.1-23.v51c4e2c879c8"
          - name: checks-api
            version: "1.7.0"
          - name: cloudbees-folder
            version: "6.15"
          - name: command-launcher
            version: "1.6"
          - name: config-file-provider
            version: "3.8.0"
          - name: credentials
            version: "2.5"
          - name: credentials-binding
            version: "1.25"
          - name: display-url-api
            version: "2.3.5"
          - name: docker-workflow
            version: "1.26"
          - name: docker-commons
            version: "1.17"
          - name: durable-task
            version: "1.37"
          - name: echarts-api
            version: "5.1.0-2"
          - name: extended-choice-parameter
            version: "0.82"
          - name: email-ext
            version: "2.83"
          - name: font-awesome-api
            version: "5.15.3-2"
          - name: git
            version: "4.7.2"
          - name: git-client
            version: "3.7.2"
          - name: git-server
            version: "1.9"
          - name: handlebars
            version: "3.0.8"
          - name: http_request
            version: "1.9.0"
          - name: jackson2-api
            version: "2.12.3"
          - name: jdk-tool
            version: "1.5"
          - name: junit
            version: "1.50"
          - name: jquery
            version: "1.12.4-1"
          - name: jquery-detached
            version: "1.2.1"
          - name: jquery3-api
            version: "3.6.0-1"
          - name: jsch
            version: "0.1.55.2"
          - name: managed-scripts
            version: "1.5.4"
          - name: mailer
            version: "1.34"
          - name: managed-scripts
            version: "1.5.4"
          - name: mattermost
            version: "3.1.1"
          - name: matrix-project
            version: "1.19"
          - name: momentjs
            version: "1.1.1"
          - name: mqtt-notification-plugin
            version: "1.8"
          - name: nodejs
            version: "1.4.0"
          - name: Office-365-Connector
            version: "4.15.0"
          - name: pipeline-aggregator-view
            version: "1.11"
          - name: pipeline-build-step
            version: "2.13"
          - name: pipeline-graph-analysis
            version: "1.11"
          - name: pipeline-input-step
            version: "2.12"
          - name: pipeline-milestone-step
            version: "1.3.2"
          - name: pipeline-model-declarative-agent
            version: "1.1.1"
          - name: pipeline-model-definition
            version: "1.8.5"
          - name: pipeline-model-api
            version: "1.8.5"
          - name: pipeline-model-extensions
            version: "1.8.5"
          - name: pipeline-rest-api
            version: "2.19"
          - name: pipeline-stage-step
            version: "2.5"
          - name: pipeline-stage-tags-metadata
            version: "1.8.5"
          - name: pipeline-stage-view
            version: "2.19"
          - name: pipeline-utility-steps
            version: "2.8.0"
          - name: plain-credentials
            version: "1.7"
          - name: plugin-util-api
            version: "2.2.0"
          - name: popper-api
            version: "1.16.1-2"
          - name: rebuild
            version: "1.32"
          - name: scm-api
            version: "2.6.4"
          - name: script-security
            version: "1.77"
          - name: ssh-credentials
            version: "1.19"
          - name: ssh-steps
            version: "2.0.0"
          - name: ssh-slaves
            version: "1.32.0"
          - name: snakeyaml-api
            version: "1.27.0"
          - name: structs
            version: "1.23"
          - name: token-macro
            version: "2.15"
          - name: trilead-api
            version: "1.0.13"
          - name: workflow-api
            version: "2.44"
          - name: workflow-basic-steps
            version: "2.23"
          - name: workflow-cps
            version: "2.92"
          - name: workflow-cps-global-lib
            version: "2.19"
          - name: workflow-durable-task-step
            version: "2.39"
          - name: workflow-job
            version: "2.41"
          - name: workflow-multibranch
            version: "2.24"
          - name: workflow-scm-step
            version: "2.12"
          - name: workflow-step-api
            version: "2.23"
          - name: workflow-support
            version: "3.8"
          - name: active-directory
          - name: ansicolor
            version: "0.7.5"
          - name: audit-trail
          - name: antisamy-markup-formatter
          - name: atlassian-bitbucket-server-integration
            version: "2.1.3"
          - name: basic-branch-build-strategies
          - name: blueocean
          - name: build-timeout
          - name: build-monitor-plugin
          - name: copyartifact
          - name: description-setter
          - name: disk-usage
          - name: docker 
          - name: htmlpublisher
          - name: git-parameter
          - name: greenballs
          - name: groovy
          - name: jira
          - name: job-dsl
          - name: leastload
          - name: list-git-branches-parameter
          - name: lockable-resources
          - name: matrix-auth
          - name: metrics
          - name: monitoring
          - name: parameterized-trigger
          - name: prometheus
          - name: pyenv-pipeline
            version: "2.1.2"
          - name: simple-theme-plugin
          - name: stashNotifier
          - name: subversion
          - name: support-core
          - name: test-results-analyzer
          - name: tfs
          - name: timestamper
          - name: validating-string-parameter
          - name: versioncolumn
          - name: xunit
          - name: workflow-aggregator
          - name: ws-cleanup
          # install CasC last to prevent CasC bootup errors that WILL occur
          # when some other plugins in this list failed to install
          - name: configuration-as-code
            version: "1.51"
          - name: configuration-as-code-groovy
            version: "1.1"
```
