### ISSUE TITLE
Merge yaml trees before applying configuration

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#184]
follow up for colliding configuration as noticed by @batmat on #150 

If we have two yaml files:
```yaml
jenkins:
  systemMessage: "Welcome to Jenkins Essentials!"
  numExecutors: 0
```
and
```yaml
jenkins:
  numExecutors: 5
```

Both will be loaded and `numExecutors` will be set based on latest value read, depending filesystem ordering (!). We need to detect this unsafe situation, break ("fail fast") and report diagnostic informations (conflicting attribute, line in files).

Another issue exists if a component configuration is split in two file, but setting it fully replace the component (which happens with for most components but root `jenkins`). For sample :
```yaml
tool:
  git:
    installations:
      - name: git
        home: /bin/git
```
+
```yaml
tool:
  git:
    installations:
      - name: anothergit
        home: /usr/local/bin/git.sh
```
Loading this configuration will set a single element list as git installations, not merging them together.

We have to merge the yaml trees before we apply configuration. 
There's no native support for this purpose in SnakeYaml, but on the other hand we probably want to get more control on this merge process, as well as track where each branch/leaf comes from (file / path / line number ?) to offer diagnostic message.
