### ISSUE TITLE
How to configure the build_agents with NonVerifyingKeyVerificationStrategy

### ISSUE THREAD

**Issue by duhuangwen** [jenkinsci/configuration-as-code-plugin#1915]
### Describe your use-case which is not covered by existing documentation.

this is my configuration with NonVerifyingKeyVerificationStrategy .
jenkins:
  nodes:
    - permanent:
        labelString: "linux docker test"
        mode: NORMAL
        name: "utility-node"
        remoteFS: "/home/user1"
        retentionStrategy: "always"
        nodeDescription: "test1"
        launcher:
          ssh:
            credentialsId: "node1"
            host: "192.168.21.128"
            javaPath: "/home/user1/jdk1.8/bin/java"
            port: "22"
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"

but  I get the message "SSH Host Key Verifiers are not configured for all SSH agents on this Jenkins instance. This could leave these agents open to man-in-the-middle attacks. [Update your agent configuration](http://192.168.21.128:8090/jenkins/computer/) to resolve this." in my jenkins service。

**Comment by mathieucoavoux** [comment]
Hi,
You may try with the following option:
```
jenkins:
  nodes:
    - name: "utility-node"
      labelString: "linux docker test"
      mode: NORMAL
      remoteFS: "/home/user1"
      retentionStrategy: "always"
      nodeDescription: "test1"
      launcher:
      ssh:
      credentialsId: "node1"
      host: "192.168.21.128"
      javaPath: "/home/user1/jdk1.8/bin/java"
      port: "22"
jenkins:
  nodes:
    - name: "utility-node"
      labelString: "linux docker test"
      mode: NORMAL
      remoteFS: "/home/user1"
      retentionStrategy: "always"
      nodeDescription: "test1"
      launcher:
      ssh:
      credentialsId: "node1"
      host: "192.168.21.128"
      javaPath: "/home/user1/jdk1.8/bin/java"
      port: "22"
      sshHostKeyVerificationStrategy:
        manuallyTrustedKeyVerificationStrategy:
          requireInitialManualTrust: "alse
```
This has been documented [here](https://github.com/jenkinsci/configuration-as-code-plugin/blob/a6983ff60e0cf198ce02d7992bcba927197174db/demos/build_agents/README.md?plain=1#L37)
