### ISSUE TITLE
Why are we getting ambiguous entries errors from authorizationStrategy matrix?

### ISSUE THREAD

**Issue by pamgluss-slack** [jenkinsci/configuration-as-code-plugin#1943]
### Your checklist for this issue

- [x] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [x] Jenkins version
- [x] Plugin version
- [ ] OS
- [x] Reproduction steps

### Description
Jenkins Version: 2.319.1-jdk11
Plugin Version: 2.9.2-29.v717aac953ff3

We have a J2 file for our authorization matrix that looks something like this:
```
  authorizationStrategy:
    globalMatrix:
      permissions:
        - 'Overall/Administer:jenkins_admin'
        - 'Overall/Read:build_webapp'
        - ...
```

But when I go to /configureSecurity/ and look at the resulting matrix, I see this:

<img width="396" alt="Screen Shot 2022-04-05 at 3 08 59 PM" src="https://user-images.githubusercontent.com/63604061/161858309-92b39034-6701-4e18-9126-6e9b2dbb4a44.png">

The docs for this part of the plugin seem to only cover the case of being anonymous or being "authorized" -- eg https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/matrix-auth#configure-matrix-authorization-strategy -- and not the case where we might be using custom groups. 

What might I be missing?
