### ISSUE TITLE
Role strategy plugin broken

### ISSUE THREAD

**Issue by jzielke84** [jenkinsci/configuration-as-code-plugin#1978]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```

Jenkins: 2.349
OS: Linux - 4.19.0-20-amd64
---
ace-editor:1.1
analysis-model-api:10.10.1
ansible:1.1
ansicolor:1.0.1
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-user-vars-plugin:1.8
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
categorized-view:1.12
checks-api:1.7.4
cloudbees-bitbucket-branch-source:773.v4b_9b_005b_562b_
cloudbees-folder:6.722.v8165b_a_cf25e9
command-launcher:81.v9c2cb_cb_db_392
config-file-provider:3.10.0
configuration-as-code:1429.v09b_044a_c93de
credentials:1126.ve05618c41e62
credentials-binding:523.vd859a_4b_122e6
data-tables-api:1.11.4-4
display-url-api:2.3.6
durable-task:496.va67c6f9eefa7
echarts-api:5.3.2-2
extended-read-permission:3.2
extensible-choice-parameter:1.8.0
external-monitor-job:191.v363d0d1efdf8
favorite:2.4.1
font-awesome-api:6.1.1-1
forensics-api:1.13.0
git:4.11.3
git-client:3.11.0
git-server:1.11
github:1.34.3
github-api:1.303-400.v35c2d8258028
github-branch-source:1628.vb_2f51293cb_78
gitlab-plugin:1.5.32
greenballs:1.15.1
h2-api:1.4.199
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
jackson2-api:2.13.3-285.vc03c0256d517
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-6
jaxb:2.3.6-1
jdk-tool:1.5
jenkins-design-language:1.25.5
jersey2-api:2.35-8
jjwt-api:0.11.2-71.v2722b_b_06a_2a_f
jnr-posix-api:3.1.7-3
job-dsl:1.79
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1.63
ldap:2.10
lockable-resources:2.15
mailer:414.vcc4c33714601
matrix-auth:3.1.2
matrix-project:771.v574584b_39e60
momentjs:1.1.1
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.8
pipeline-build-step:2.18
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-input-step:448.v37cea_9a_10a_70
pipeline-maven:3.10.0
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2081.v3919681ffc1e
pipeline-model-definition:2.2081.v3919681ffc1e
pipeline-model-extensions:2.2081.v3919681ffc1e
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2081.v3919681ffc1e
pipeline-stage-view:2.24
pipeline-utility-steps:2.12.1
plain-credentials:1.8
plugin-util-api:2.17.0
popper-api:1.16.1-3
popper2-api:2.11.5-2
postbuildscript:3.1.0-375.v3db_cd92485e1
pubsub-light:1.16
resource-disposer:0.19
role-strategy:484.v8a_a_e4b_d785fd
schedule-build:280.vc5c0311537f6
scm-api:608.vfa_f971c5a_a_e9
script-security:1172.v35f6a_0b_8207e
simple-theme-plugin:103.va_161d09c38c7
snakeyaml-api:1.30.1
sse-gateway:1.25
ssh-credentials:277.v95c2fec1c047
sshd:3.237.v883d165a_c1d3
structs:318.va_f3ccb_729b_71
token-macro:293.v283932a_0a_b_49
trilead-api:1.57.v6e90e07157e1
variant:1.4
workflow-aggregator:578.vf9a_f99755f4a_
workflow-api:1153.vb_912c0e47fb_a_
workflow-basic-steps:948.v2c72a_091b_b_68
workflow-cps:2692.v76b_089ccd026
workflow-cps-global-lib:583.vf3b_454e43966
workflow-durable-task-step:1139.v252a_e12e8463
workflow-job:1181.va_25d15548158
workflow-multibranch:712.vc169a_1387405
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:625.vd896b_f445a_f8
workflow-support:820.vd1a_6cc65ef33
ws-cleanup:0.42 
```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Debian Buster

### Reproduction steps

Add configuration like:

```yaml
jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: admin
            description: "Role admin"
            pattern: ".*"
            assignments:
              - "g_jenkins_admin"
            permissions:
              - "Agent/Build"
              - "Agent/Configure"
              - "Agent/Connect"
              - "Agent/Create"
              - "Agent/Delete"
              - "Agent/Disconnect"
              - "Agent/Provision"
              - "Credentials/Create"
              - "Credentials/Delete"
              - "Credentials/ManageDomains"
              - "Credentials/Update"
              - "Credentials/View"
              - "Job/Build"
              - "Job/Cancel"
              - "Job/Configure"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Discover"
              - "Job/Move"
              - "Job/Read"
              - "Job/Workspace"
              - "Lockable Resources/Reserve"
              - "Lockable Resources/Unlock"
              - "Overall/Administer"
              - "Overall/Read"
              - "Run/Delete"
              - "Run/Replay"
              - "Run/Update"
              - "SCM/Tag"
              - "View/Configure"
              - "View/Create"
              - "View/Delete"
              - "View/Read"
        items:
          - name: role_acd
            description: "Role role_acd"
            pattern: "(^.*_deploy_wildfly_.*)"
            assignments:
              - "dev1"
            permissions:
              - "Job/Build"
              - "Job/Cancel"
              - "Job/Discover"
              - "Job/Read"
              - "Job/Workspace"
              - "View/Read"
              - "Overall/Read"
```

### Expected Results

Deploy configuration

### Actual Results

systemd log shows:
```
May 31 10:32:13 jenkinsserver jenkins[23497]: Caused: io.jenkins.plugins.casc.ConfiguratorException: roleDefinition: Failed to construct instance of class org.jenkinsci.plugins.rolestrategy.casc.RoleDefinition.
May 31 10:32:13 jenkinsserver jenkins[23497]:  Constructor: public org.jenkinsci.plugins.rolestrategy.casc.RoleDefinition(java.lang.String,java.lang.String,java.lang.String,java.util.Collection,java.util.Collection).
May 31 10:32:13 jenkinsserver jenkins[23497]:  Arguments: [java.lang.String, null, java.lang.String, java.util.ArrayList, java.util.ArrayList].
May 31 10:32:13 jenkinsserver jenkins[23497]:  Expected Parameters: name java.lang.String, description java.lang.String, pattern java.lang.String, permissions java.util.Collection<java.lang.String>, assignments java.util.Collection<java.lang.String>
```
