### ISSUE TITLE
Missing GitHub OAuth plugin matrix-based authorization examples

### ISSUE THREAD

**Issue by nlucero** [jenkinsci/configuration-as-code-plugin#1980]
### Describe your use-case which is not covered by existing documentation.

The [GitHub OAuth plugin](https://plugins.jenkins.io/github-oauth/) allows to define authorization based on username, organization and/or team. From [their docs](https://github.com/jenkins-infra/plugins-wiki-docs/tree/master/github-oauth#matrix-based-authorization-strategy):

> You can configure authorization based on GitHub users, organizations, or teams.
> - `username` - give permissions to a specific GitHub username.
> - `organization` - give permissions to every user that belongs to a specific GitHub organization.
> - `organization*team` - give permissions to a specific GitHub team of a GitHub organization. Notice that organization and team are separated by an asterisk (*).

It's not clear how this should be set up in the matrix configuration. Can we please add some examples for each of these cases? The [global-matrix-auth](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/global-matrix-auth) example seems to just copy+paste that part of the plugin docs but doesn't show how it should be used.

**Comment by jetersen** [comment]
@nlucero have you tried configuring it and exporting the config?
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configExport.md

**Comment by nlucero** [comment]
@jetersen I did but I still have the same problem: I don't know what to put on the `User/group` part of the matrix's row. For example, if I want to grant permissions for everyone in my organization, should `myorg` be a _user_? Should it be a _group_? What if I want to grant team-level permissions (`organization*team`)?

**Comment by jetersen** [comment]
According to matrix auth docs and test it should be `GROUP:Overall/Read:myorg` so that is not ambiguous see test example here 
https://github.com/jenkinsci/matrix-auth-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/matrixauth/integrations/casc/configuration-as-code.yml
https://www.jenkins.io/doc/book/security/managing-security/

**Comment by nlucero** [comment]
Yes, I tried that without success. If I do that, I get a `<username >is missing the Overall/Read permission` even if `username` belongs to the org, so it doesn't seem to be picking it up as the organization name.

**Comment by samchoraria** [comment]
For anyone looking for a `CASC` example for Github OAuth group assignment to matrix permissions:-

- Ensure your **Org** level Github OAuth App is configured & generate a client secret.
- Add an authorization strategy & the security realm entry for Github OAuth:-
```
jenkins:
  ...
  authorizationStrategy:
    projectMatrix:
      entries:
      - group:
          name: "orgname*teamname1"
          permissions:
          - "Overall/Administer"
      - group:
          name: "orgname*teamname2"
          permissions:          
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Read"
          - "Overall/Read"          
          - "View/Read"
  ...
  securityRealm:
    github:
      clientID: myclientid1234567890
      clientSecret: mysupersecretclientsecret1234
      githubApiUri: "https://api.github.com"
      githubWebUri: "https://github.com"
      oauthScopes: "read:org,user:email"
```
