### ISSUE TITLE
Azure AD plugin

### ISSUE THREAD

**Issue by eabern2** [jenkinsci/configuration-as-code-plugin#2126]
### Describe your use-case which is not covered by existing documentation.

Azure AD plugin doesn't have an example or demo repository.  Can this be added?

**Comment by timja** [comment]
There's an example here:
https://github.com/jenkinsci/azure-ad-plugin/blob/master/src/test/resources/com/microsoft/jenkins/azuread/integrations/casc/configuration-as-code.yml

It's not expected that all plugins add documentation here as for most plugins you just need to configure them in the UI and export their configuration

**Comment by nfalco79** [comment]
I can show my configuration
```yaml
controller:
  JCasC:
    # Ignored if securityRealm is defined in controller.JCasC.configScripts
    securityRealm: |-
      azure:
        cacheDuration: 3600
        clientId: ${secret-credentials-azureAD-key}
        clientSecret: ${secret-credentials-azureAD-secret}
        tenant: ${secret-credentials-azureAD-tenant}
```

to generate the client id-secret read the documentation in the AzureAD plugin. I think this issue can be closed
