### ISSUE TITLE
Does not select correct constructor of amazon-ecs plugin

### ISSUE THREAD

**Issue by anthonylau** [jenkinsci/configuration-as-code-plugin#2137]
I'm not sure if this is an expected behaviour

Jenkins version [Jenkins 2.371]
Plugin version [1512.vb_79d418d5fc8]
Docker Image [jenkins/jenkins:2.361.1-lts]
Amazon ECS Plugin Version [1.41] https://plugins.jenkins.io/amazon-ecs/ 

adding yml config
```yml
clouds:
  - ecs:
      allowedOverrides: "inheritFrom,label,memory,cpu,image"
      cluster: "arn:aws:ecs:xxxxx:xxxx:cluster/xxxx"
      jenkinsUrl: "http://192.168.1.1:18080/"
      name: "jenkins-aws-fargate"
      regionName: "ap-southeast-1"
      taskPollingIntervalInSeconds: 3
```

Error

> io.jenkins.plugins.casc.ConfiguratorException: credentialsId is required to configure class com.cloudbees.jenkins.plugins.amazonecs.ECSCloud

The `credentialsId` is optional. The configuration works if configure via UI. There is another constructor for it https://github.com/jenkinsci/amazon-ecs-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java#L108

Does anyone managed to config the amazon-ecs plugin without the `credentialsId` ?
