### ISSUE TITLE
Version 0.6-alpha broke role-based authorization that contains global roles only

### ISSUE THREAD

**Issue by alapshin** [jenkinsci/configuration-as-code-plugin#214]
If jenkins.yaml contains role-based authorization configuration with global roles only
```
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: 12345

  # Configure role-based authorization strategy
  authorizationStrategy:
    roleStrategy:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"          
```

Then this setup doesn't work in 0.6-alpha (however it worked in 0.4-alpha)
In 0.6-alpha Jenkins fails to start with exception
```
Caused by: java.lang.NullPointerException
jenkins    |    at org.jenkinsci.plugins.casc.integrations.rolebasedauth.RoleBasedAuthorizationStrategyConfigurator.retrieveRoleMap(RoleBasedAuthorizationStrategyConfigurator.java:71)
jenkins    |    at org.jenkinsci.plugins.casc.integrations.rolebasedauth.RoleBasedAuthorizationStrategyConfigurator.configure(RoleBasedAuthorizationStrategyConfigurator.java:61)
jenkins    |    at org.jenkinsci.plugins.casc.integrations.rolebasedauth.RoleBasedAuthorizationStrategyConfigurator.configure(RoleBasedAuthorizationStrategyConfigurator.java:33)
jenkins    |    at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:81)
jenkins    |    at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:34)
jenkins    |    at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:188)
jenkins    |    at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:44)
jenkins    |    at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:24)
jenkins    |    at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:335)
jenkins    |    at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:280)
jenkins    |    at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:252)
jenkins    |    at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:155)
jenkins    |    at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:134)

```

As far as I can tell it is caused by this change:
https://github.com/jenkinsci/configuration-as-code-plugin/commit/f7cfe0d2a32c6f31d76dea5322c45023d7eefc4a#diff-c4e07dfa3bcbf094062d1295a61d5ffbL70

Missing `items` or `agents` field causes NPE because new code tries to convert them to sequence without checking for their existence.

Specifying  empty project and agent roles  like this solves problem:

```
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: 12345

  # Configure role-based authorization strategy
  authorizationStrategy:
    roleStrategy:
      roles:
        items: []
        agents: []
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"          
```
