### ISSUE TITLE
authorizationStrategy being ignored in JCasC

### ISSUE THREAD

**Issue by hilafish** [jenkinsci/configuration-as-code-plugin#2187]
### Jenkins and plugins versions report

Hi,

I'm trying to set up authorizationStrategy to Matrix-Based security via JCasC, but it's being ignored and the default below is set-
```
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
```
I've installed the plugins below (with `installLatestPlugins: true` set)-
```
    - matrix-project
    - matrix-auth
```
(configuration-as-code plugin already installed and working as expected for all other configurations I've set)
and then I tried setting it like that-
```
controller:
  JCasC:
    jenkins:   
      authorizationStrategy: |-
        globalMatrix:
          permissions:
            - "Overall/Read:anonymous"
            - "Overall/Administer:authenticated"
```
Based on these docs:
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/global-matrix-auth
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/matrix-auth
but it doesn't work.
I also tried without the `|-` near the `authorizationStrategy:` directive, didn't help.

I also tried like this:
```
controller:
  JCasC:
    authorizationStrategy: |-
      globalMatrix:
        permissions:
          - "Overall/Read:anonymous"
          - "Overall/Administer:authenticated"
```
Based on this documentation:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md#jenkins-plugins
which doesn't mention the `jenkins:` directive, but it didn't work.

Here it also says that it could be defined under `configScripts`-
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L347
But when I try that, I get syntax error.

Why doesn't it work? I don't see anything about it in the Jenkins pod log.

Any help would be appreciated :)

### What Operating System are you using (both controller, and any agents involved in the problem)?

EKS version 1.24.

### Reproduction steps

1. set up jenkins chart deployment with JCasC plugin usage, either of the below-
```
controller:
  JCasC:
    jenkins:   
      authorizationStrategy: |-
        globalMatrix:
          permissions:
            - "Overall/Read:anonymous"
            - "Overall/Administer:authenticated"
```

```
controller:
  JCasC:
    authorizationStrategy: |-
      globalMatrix:
        permissions:
          - "Overall/Read:anonymous"
          - "Overall/Administer:authenticated"
```

2. manage jenkins-> configuration as code-> view configuration, see the default is kept-
```
jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
``` 

### Expected Results

authorizationStrategy would be set to "Matrix-based security" with defined permissions.

### Actual Results

authorizationStrategy configuration is ignored, and the default is set and used-
```
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
```

**Comment by hilafish** [comment]
And.. I made it work by using a reference from another open issue (https://github.com/jenkinsci/configuration-as-code-plugin/issues/2185).
It should be set under `JCasC:` directive directly:
```
  JCasC:
    authorizationStrategy: |-
      globalMatrix:
        permissions:
          - "Overall/Read:anonymous"
          - "Overall/Administer:authenticated"   
```

Let me know if you want me to open a PR to fix the documentation.
