### ISSUE TITLE
CasC exporter does not handle ownership plugin

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#222]
CasC exporter ignores many fields for views

Source Groovy Script:

```groovy
// Initializes Views on the instance, including the default one.
import com.synopsys.arc.jenkins.plugins.ownership.jobs.JobOwnerColumn
import com.synopsys.arc.jenkins.plugins.ownership.jobs.OwnershipJobFilter
import jenkins.model.Jenkins
import hudson.model.ListView
import hudson.views.ListViewColumn

// Additional view, which also shows owners
ListView withOwnership = new ListView("With ownership")
List<ListViewColumn> columns = new LinkedList<>(withOwnership.getColumns())
columns.add(3, new JobOwnerColumn())
withOwnership.with {
    includeRegex = ".*"
    columns = columns
}
Jenkins.instance.addView(withOwnership)

// Default view, which recursively shows jobs owned by the current user
ListView myJobs = new ListView("My jobs")
columns = new LinkedList<>(withOwnership.getColumns())
columns.add(3, new JobOwnerColumn())
myJobs.with {
    includeRegex = ".*"
    recurse = true
    columns = columns
}
myJobs.jobFilters.add(new OwnershipJobFilter("@Me", true))
Jenkins.instance.addView(myJobs)

Jenkins.instance.setPrimaryView(myJobs)
```

Produced YAML by exporter:

```yml
  views:
  - list:
      includeRegex: ".*"
      recurse: true
  - list:
      includeRegex: ".*"
  - "all"
```

**Comment by oleg-nenashev** [comment]
YAML just won't work as you may guess

**Comment by uhafner** [comment]
It even does not remember the selected dashboards in the dashboard view :-( Quite use less for views up to now...

**Comment by casz** [comment]
After #838 this should be exported correctly :laughing: 

```yml
jenkins:
  views:
  - all:
      name: "all"
  - list:
      columns:
      - "status"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      name: "listView"
  viewsTabBar: "standard"
```
