### ISSUE TITLE
CasC Exporter generates wrong property for Ownership plugin

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#224]
If OwnershipProperty from Ownership Plugin is set for a node, CasC Exporter produces a weird single-string output:

```yaml
  nodeProperties:
  - "owner"
  - jobRestrictionProperty:
      jobRestriction:
```

Clearly Ownership property does not support CasC well, but maybe it should be skipped or indicated as error
