### ISSUE TITLE
systemMessage color

### ISSUE THREAD

**Issue by KataaM** [jenkinsci/configuration-as-code-plugin#2292]
### What feature do you want to see added?

It would be great to possibly use some html colors in the systemMessage of our Jenkins.

**Comment by somiljain2006** [comment]
HTML in systemMessage is already passed through correctly. 

When Jenkins is configured with a markup formatter (e.g., rawHtml), the HTML is rendered as expected. Without a markup formatter, Jenkins displays it as plain text. 

For reference, you can configure it like this:
```yaml
jenkins:
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  systemMessage: |
    <span style="color:red;font-weight:bold">
      Hello from JCasC
    </span>
```
