### ISSUE TITLE
Working with different environments, load files specific to environment

### ISSUE THREAD

**Issue by davorceman** [jenkinsci/configuration-as-code-plugin#2502]
### What feature do you want to see added?

I'm trying to set Jenkins in Docker with JCasC.
And I would like to use the same image for multiple environments.

I can handle a lot with injecting variables "${SOME_VAR}" in yml files, but that does not solving all cases.
For example, I have different permanent nodes in environments.

it would be great if we can use something like

```
jenkins:
  nodes:
    << !include ${ENVIRONMENT}-nodes.yml
```

where ${ENVIRONMENT}-nodes.yml has a list of permanent nodes
```
- permanent:
     labelString: "node-1"
     name: "node-1"
     ....
- permanent:
     labelString: "node-2"
     name: "node-2"
     ....
```

Also, somewhere I would like to configure some plugins, and in some environment I would skip those

Is there already some way I can use which is natively supported by CasC, without introducing some other tools for templating?
