### ISSUE TITLE
JCasC in Kubernetes

### ISSUE THREAD

**Issue by danielstankw** [jenkinsci/configuration-as-code-plugin#2572]
### Jenkins and plugins versions report

Hi,
I am using Jenkins deployed in Kubernetes.
I also used CasC which I define in values.yaml section of the helm chart, by adding it to the configScripts section.
It works but its not optimal. I would like to have CaSc defined outside of values.yaml and inject it, I tried:

Placing casc.yaml config files in the folder of "/var/jenkins_home/casc_config/jenkins.yaml but I wasnt able to get it to work
Similarly adding git repo with yamls in ConfigUrls didnt work.
I guess issue could be due to lack of permissions or wrong setup, would anyone who got it to work be able to share with me how they configured it?

JCasC:
    # -- Enables default Jenkins configuration via configuration as code plugin
    defaultConfig: true

    # If true, the init container deletes all the plugin config files and Jenkins Config as Code overwrites any existing configuration
    # -- Whether Jenkins Config as Code should overwrite any existing configuration
    overwriteConfiguration: false
    # -- Remote URLs for configuration files.
    configUrls: []
    # - https://acme.org/jenkins.yaml
    # -- List of Jenkins Config as Code scripts
    configScripts: 
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server. This Jenkins is configured and managed 'as code'.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu

### Reproduction steps

xxx

### Expected Results

xxx

### Actual Results

xxx

### Anything else?

xxx

**Comment by matt-locker** [comment]
@danielstankw 
Have you set the environment?
CASC_JENKINS_CONFIG /var/jenkins_home/casc_config

Is the plugin installed?
jenkins-plugin-cli -f /tmp/plugins.txt

plugins.txt must contain configuration-as-code

**Comment by somiljain2006** [comment]
The behavior you are seeing is likely related to how the Jenkins Helm chart handles JCasC configuration sources rather than a JCasC plugin issue itself.

Two approaches that generally work well are:

1. **ConfigMaps + JCasC auto-reload**

   * Enable the JCasC reload sidecar.

   ```yaml
   controller:
     sidecars:
       configAutoReload:
         enabled: true

   rbac:
     create: true
   ```

   * Store your JCasC YAML in an external ConfigMap and label it according to your Helm chart configuration.

   ```yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: external-jenkins-casc
     labels:
       jenkins-jenkins-config: "true"
   data:
     jenkins.yaml: |
       jenkins:
         systemMessage: "Configured via external ConfigMap"
   ```

   * The sidecar will mount the files and trigger a reload when they change.

2. **Git repository + InitContainer**

   * Use an init container to clone a repository containing your JCasC YAML files.
   * Copy the files into the JCasC configuration volume before Jenkins starts.

   ```yaml
   controller:
     customInitContainers:
       - name: git-clone-casc
         image: alpine/git
         command:
           - /bin/sh
           - -c
           - |
             git clone https://github.com/<org>/<repo>.git /tmp/casc
             cp /tmp/casc/*.yaml /var/jenkins_home/casc_configs/
         volumeMounts:
           - name: sc-config-volume
             mountPath: /var/jenkins_home/casc_configs
   ```

A couple of additional things to verify:

* The default JCasC directory used by the Helm chart is typically `/var/jenkins_home/casc_configs` (plural).
* `configUrls` expects one or more URLs that directly serve JCasC YAML content. A GitHub repository URL or GitHub UI page URL will not work because they return HTML, not a YAML configuration file.
