### ISSUE TITLE
CasC with multiple containers

### ISSUE THREAD

**Issue by danielstankw** [jenkinsci/configuration-as-code-plugin#2647]
Looking for someone to share their config where there are two containers in one pod template.
I have set it up using UI, and than generated CasC file which I used in my values.yaml (helm installation) but it doesnt work and one container overwrites the another one - any help is much appreciated

**Comment by somiljain2006** [comment]
I tested a multi-container pod template using the Jenkins Helm chart

The following `values.yaml` configuration worked successfully for me:

```yaml
agent:
  enabled: true
  podTemplates:
    multi-container-agent: |
      - name: "multi-container-agent"
        label: "jenkins-multi-agent"
        serviceAccount: "default"
        containers:
          - name: "maven"
            image: "maven:3.9.6-eclipse-temurin-17"
            command: "sleep"
            args: "99d"
            ttyEnabled: true
          - name: "golang"
            image: "golang:1.22"
            command: "sleep"
            args: "99d"
            ttyEnabled: true
```

To verify it, I ran the following Pipeline:

```groovy
pipeline {
    agent { label 'jenkins-multi-agent' }
    stages {
        stage('Test Dual Containers') {
            steps {
                container('maven') {
                    sh 'mvn --version'
                }
                container('golang') {
                    sh 'go version'
                }
            }
        }
    }
}
```

Results:

* `helm template` rendered both containers correctly under the same pod template.
* Jenkins successfully loaded the pod template via JCasC.
* Kubernetes created a pod containing `jnlp`, `maven`, and `golang`.
* The Pipeline executed successfully in both containers.
