### ISSUE TITLE
Update matrix-auth example

### ISSUE THREAD

**Issue by anthony-chu** [jenkinsci/configuration-as-code-plugin#2678]
### Describe your use-case which is not covered by existing documentation.

Since version 3.2 of the `matrix-auth` plugin was released, the JCasC syntax for configuring permissions has been updated. The [current documentation](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/global-matrix-auth/README.md) still refers to the pre-3.2 syntax.

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

Here is the example given in the `matrix-auth` 3.2 release notes:
```yaml
authorizationStrategy:
  projectMatrix:
    entries:
      - user:
          name: "admin"
          permissions:
            - "Overall/Administer"
      - group:
          name: "authenticated"
          permissions:
            - "Overall/Read"
```

see https://github.com/jenkinsci/matrix-auth-plugin/releases/tag/matrix-auth-3.2
