### ISSUE TITLE
Add support of the plugin's self-configuration in jenkins.yaml

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#274]
There are several cases when plugin users may want to configure JCasC's behavior.

Examples:
* Set behavior when accessing restricted fields
* Set behavior when accessing deprecated fields
* Set behavior on warnings and section configuration errors...

It would be great to have a configuration section which allows altering the behavior... directly from JCasC plugin's yaml.

E.g.:

```yaml
casc:
  setters:
    onDeprecated: warn
    onRestricted: warn
    onError: fail
jenkins:
  ...
```
