### ISSUE TITLE
support custom update center

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#299]
configuration-as-code section in jenkins.yaml could be used to define custom update center url:

```yaml
configuration-as-code:
   version: 1
   updateCenterUrl: httpps://my-jenkins-uc.myorg.com
```

**Comment by ndeloof** [comment]
what's wrong with 
```yaml
plugins:
   sites:
      - id: default
        url: httpps://my-jenkins-uc.myorg.com
```

please note UpdateCenter design is not restricted to a single update site (despite lack of UI for management)
