### ISSUE TITLE
allow to set plugin URL for installation

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#303]
As suggested at JUC Paris

```yaml
plugins:
  required:
    monplugin: http://acme.com/monplugin.jpi
```
