### ISSUE TITLE
Add maven installation not clear

### ISSUE THREAD

**Issue by smueller18** [jenkinsci/configuration-as-code-plugin#336]
I have problems adding a maven tool config in the tools section of the yml config. In the reference, the maven tool must be a `GlobalMavenConfig` and not a `DescriptorImpl` like the git tool.
Can you give me a hint, how the yaml must look like?

A snippet analogoes to git does not work:
```yml
tool:
  maven:
    installations:
      - name: maven
        home: /usr/share/maven
```

I am using the latest Jenkins version with the latest configuration-as-code and maven-plugin version installed.
