### ISSUE TITLE
Setting pullStrategy of DockerTemplateBase is not possible

### ISSUE THREAD

**Issue by smueller18** [jenkinsci/configuration-as-code-plugin#342]
I tried setting the pullStrategy in Docker templates with
```
jenkins:
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins/slave"
              pullStrategy: PULL_ALWAYS
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
```
but the pull strategy enum is not parsed correctly. Is it possible to implement this feature?
