### ISSUE TITLE
Ability to configure Users

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#35]
Need some way to configure users and UserProperties, including (but not limited) to `HudsonPrivateSecurityRealm$Details` to pre-configure admin user with a password

**Comment by ndeloof** [comment]
I'd like we can write this :

```yaml 
users:
  - name: "admin"
    properties:
      - password: "1234"
      - emailAddress: "admin@acme.com"
```
