### ISSUE TITLE
Minimal JCasC yaml config ineffectual wrt. matrix-auth plugin

### ISSUE THREAD

**Issue by x10an14** [jenkinsci/configuration-as-code-plugin#361]
Hi! Ref. conversation with @casz [in gitter](https://gitter.im/jenkinsci/configuration-as-code-plugin?at=5b4877ed641ecc065f9f0318), here's my minimal setup:

```yaml
jenkins:
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - name: 'anonymous'
          permissions: []
        - name: 'authenticated'
          permissions:
            - 'Overall/Read'
        - name: 'admin'
          permissions:
            - 'Overall/Administer'
  # http://yaml-multiline.info/
  systemMessage: |-
    Testing Matrix-Auth plugin
```
When I log into the newly created Jenkins instance (which I create from scratch each time, deleting everything in `docker-compose` and the `docker volume`), I see [the following](https://imgur.com/ZteKaLw).

`plugins.txt` file fed into Docker Image: (see `Dockerfile` and `docker-compose.yaml` files)
```
saml:1.0.7
matrix-auth:2.3
pipeline-model-definition:1.3.1
docker-slaves:1.0.7
pipeline-utility-steps:2.1.0
configuration-as-code:0.10-alpha
```
`docker-compose.yaml`:
```yaml
version: '3'

services:
  jenkins:
    restart: on-failure
    build:
      context: ./jenkins-master
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro  # To ensure timezone matches host
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/jenkins.yaml

volumes:
  jenkins_home:
```

`jenkins-master/Dockerfile`:
```Dockerfile
FROM jenkins/jenkins:lts
# LTS version!
# Requires something to execute `docker pull jenkins/jenkins:lts` every now and then, to stay up-to-date.
# Ref: https://hub.docker.com/r/jenkins/jenkins/tags/

# LABEL maintaner=""

COPY stb_plugins.txt /usr/share/jenkins/ref/stb_plugins.txt
RUN xargs /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/stb_plugins.txt

# Jenkins Configuration-as-Code (JCasC) settings file:
COPY jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml
```

**Comment by x10an14** [comment]
Seems to maybe be related to what @ndeloof is writing about in #352 and in https://github.com/jenkinsci/matrix-auth-plugin/pull/48.

**Comment by x10an14** [comment]
Oh, and I use 
```docker-compose down && docker-compose rm -v && docker volume rm stb-jcasc_jenkins_home \
&& docker-compose up --build --detach```
 between each Jenkins iteration, in case that has any effect on reproducing my issue.

**Comment by casz** [comment]
Do you get an expect during startup?
Also I think you can just remove anonymous

**Comment by x10an14** [comment]
Ahh, derp. That's what I get for trusting random stack overflow posts instead of checking the documentation the tool offers.

Thanks for the tip on how to disable the initial setup-wizard! =D

**Comment by casz** [comment]
This is ours and it seems to work 👍 
```yml
  authorizationStrategy:
    projectMatrix:
      grantedPermissions:
        - name: Read Only
          permissions:
            - Overall/Read
        - name: Create Agents
          permissions:
            - Overall/Administer
        - name: Admins
          permissions:
            - Overall/Administer
```
