### ISSUE TITLE
Problems with Plugins.sites syntax 

### ISSUE THREAD

**Issue by JKrag** [jenkinsci/configuration-as-code-plugin#366]
I have a problem with figuring out the plugins.sites syntax in 0.10 Alpha.
In my yaml I currently have:

```
plugins:
  sites:
  - id: "default"
    url: "http://mirror.REDACTED.com/jenkins/updates/update-center.json"
  - id: "experimental"
    url: "https://updates.jenkins.io/experimental/update-center.json"
```
As previously suggested in Gitter, and it used to work fine, but now I get a warning  in "Manage Jenkins" saying:
> Configuration as Code obsolete file format:
> 
>    /var/jenkins_home/casc/jenkins.yaml (line 193): Invalid configuration elements for type class hudson.model.UpdateSite : id,url
>    /var/jenkins_home/casc/jenkins.yaml (line 195): Invalid configuration elements for type class hudson.model.UpdateSite : id,url

Oddly enough, my export lists exactly the same syntax as mentioned above. 

If I check the generated documentation, it just says that `sites` is a "List of UpdateSite", but the docs never define what a "UpdateSite" looks like. (It is mentioned, but the section is blank).

**Comment by casz** [comment]
indents are off.

**Comment by JKrag** [comment]
Sample is copied directly from Export. I used to have different (more) indent, but all of export is indented like this, so I figured that was ok. I will change back and test again.

**Comment by ndeloof** [comment]
this has been fixed already by https://github.com/jenkinsci/configuration-as-code-plugin/commit/89fcebfbdc38a87f6b263baa3123e08c73c74a11

**Comment by deitch** [comment]
I ran into this exact same problem today. Did an export, then `curl -X POST`ed the file to the configuration-check endpoint, got large stack trace, but clear point at:

```
mapping values are not allowed here
 in org.kohsuke.stapler.RequestImpl@75e87607, line 1, column 16:
    plugins:  sites:  - id: "default"    url: "http ...
                   ^
```

Which is strange, since it is *not* a mapping:

```yml
plugins:
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
```

Any suggestions?

**Comment by deitch** [comment]
Looks like this may not be the same issue. Even if I reverse the order of `sites` and `required`, it blows up.

```yml
plugins:
  required:
    # requirement for various other plugins
    jdk-tool: 1.2
```

Error:

```
mapping values are not allowed here
 in org.kohsuke.stapler.RequestImpl@33add23d, line 1, column 19:
    plugins:  required:    # requirement for various o ...
```
