### ISSUE TITLE
Not in export: configuration-as-code settings

### ISSUE THREAD

**Issue by JKrag** [jenkinsci/configuration-as-code-plugin#368]
0.10-Alpha.

My current yaml file says:

```
configuration-as-code:
  version: "1"
  unknown: warn
  restricted: warn
  deprecation: warn
``` 

but export only contains:
```
configuration-as-code:
  version: "1"
```
