### ISSUE TITLE
Not in export: authorizationStrategy

### ISSUE THREAD

**Issue by JKrag** [jenkinsci/configuration-as-code-plugin#369]
The entire `authorizationStrategy:` section is missing from my export (in 0.10-Alpha).

I have the following in my yaml (that seems to work):
```
jenkins:
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        # - name: "anonymous"
        #   permissions:
        #     - "Overall/Administer"
        - name: "authenticated"
          permissions:
            - "Overall/Administer"
        - name: "ABC Software Administrators"
          permissions:
            - "Overall/Administer"
```
