### ISSUE TITLE
Not in export: tool section

### ISSUE THREAD

**Issue by JKrag** [jenkinsci/configuration-as-code-plugin#371]
In my yaml I have:

```
tool:
  git:
    installations:
      - name: Default
        home: git
```

but export does not contain a `tool:` section at all. (0.10-Alpha)
