### ISSUE TITLE
Kubernetes : 'imagePullSecret' not documented

### ISSUE THREAD

**Issue by nothing-fr** [jenkinsci/configuration-as-code-plugin#377]
Is it possible to use / have an example for the `imagePullSecret` parameter in a pod/container template of the Kubernetes plugin ?

I've tried to use it without success so far...
*Thanks.*

**Comment by ndeloof** [comment]
based on https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/PodTemplate.java#L480 you should be able to use:
```yaml
template:
  imagePullSecrets:
    - name: "foo"
    - name: "bar"
```

**Comment by ndeloof** [comment]
@nothing-fr awaiting your feedback

**Comment by nothing-fr** [comment]
I've checked the generated documentation, but didn't find anything on the `imagePullSecrets` param.

I've finally been able to make it work (with your help) like this : 

```yaml
        templates:
          - name: "k8s-ansible-slave"
            imagePullSecrets:
              - name: "docker_secret"
            namespace: "jenkins"
            label: "ansible"
            nodeUsageMode: EXCLUSIVE
            containers:
              - name: "jnlp"
                image: "jenkins-ansible-slave"
                alwaysPullImage: true
                workingDir: "/home/jenkins/agent"
                ttyEnabled: true
                command: ""
                args: ""
```
Thanks for your help.
