### ISSUE TITLE
Credentials inconsistency with xml file

### ISSUE THREAD

**Issue by yogeek** [jenkinsci/configuration-as-code-plugin#384]
I am not sure to understand how the credentials configuration works. 
When I load the following credentials.yml (as documented in [demos/credentials](../tree/master/demos/credentials/)) :
```
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: cred
              description: "My cred"
              username: jenkins
              password: $CRED_PASSWORD
```

the credentials are updated in Jenkins UI (all my previous credentials are gone and the one in YAML file is present) but the `credentials.yml` file is not (it still contains all previous credentials and not the new one)
So I am in a situation where the `credentials.xml` file is not in line with what the GUI shows...

What is the normal behaviour ?
Where are the credentials in the GUI retrieved from ?
