### ISSUE TITLE
Null Pointer Exception during startup when upgrading to RC1

### ISSUE THREAD

**Issue by x10an14** [jenkinsci/configuration-as-code-plugin#444]
Hi!

Problem: As specified in subject/title.
What follows are lots of details, in case any of them are relevant.

- Jenkins docker version: `jenkins/jenkins:lts` (AKA `jenkins/jenkins/:2.121.2`)
- `Dockerfile`:
```
FROM jenkins/jenkins:lts
# LTS version!
# Requires something to execute `docker pull jenkins/jenkins:lts` every now and then, to stay up-to-date.
# Ref: https://hub.docker.com/r/jenkins/jenkins/tags/

LABEL maintaner="my email at work"

COPY stb_plugins.txt /usr/share/jenkins/ref/stb_plugins.txt
RUN install-plugins.sh < /usr/share/jenkins/ref/stb_plugins.txt

# Jenkins Configuration-as-Code (JCasC) settings file:
COPY jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml
```
- `jenkins.yaml` (sensitive data replaced with '< some text/explanation >'):
```
configuration-as-code:
  version: 1
  deprecation: warn
  restricted: reject

jenkins:
  # http://yaml-multiline.info/
  systemMessage: |-
    Welcome to STB's first (alpha version of) Jenkins! =D
  securityRealm:
    ldap:
      configurations:
      - rootDN: "DC=stb,DC=local"
        server: "ldap://ad.stb.intra:389"
        displayNameAttributeName: "displayName"
        userSearch: "sAMAccountName={0}"
        managerDN: "<a valid service account username>"
        managerPasswordSecret: ${LDAP_MANAGER_PASSWORD}
  agentProtocols:
    -
  slaveAgentPort: -1
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

security:
  remotingCLI:
    enabled: false

tool:
  git:
    installations:
      - name: Default
        home: "git"

credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          scope: GLOBAL
          passphrase: ${SSH_KEY_PASSWORD}
          id: "STB_BITBUCKET_PRIVATE_SSH_KEY"
          username: ${BITBUCKET_SSH_KEY_USERNAME}
          privateKeySource:
            directEntry:
              privateKey: |-
                -----BEGIN RSA PRIVATE KEY-----
               <snipped>
                -----END RSA PRIVATE KEY-----

unclassified:
  location:
    adminAddress: "<a valid email>"   # Email address of administrator(s)
    url: "<a valid URL>"    # Canonical URL of Jenkins instance
  globalLibraries:
    libraries:
      - name: "Jenkins-Pipeline-Library"
        allowVersionOverride: true
        defaultVersion: "master"
        includeInChangesets: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "<a valid URL>"
                credentialsId: "STB_BITBUCKET_PRIVATE_SSH_KEY"
```
- `docker-compose.yaml`:
```
version: '3'

services:
  jenkins:
    restart: on-failure
    build:
      context: ./jenkins-master
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro  # To ensure timezone matches host
    ports:
      - 8080:8080
    environment:
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/jenkins.yaml
    env_file: ./jenkins-master/secrets.env

volumes:
  jenkins_home:
```

And finally, output/NPE:
```
(...)
WAR bundled plugins:


Installed plugins:
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.5-3.0
authentication-tokens:1.3
branch-api:2.0.20
cloudbees-folder:6.5.1
configuration-as-code:1.0-rc1
credentials-binding:1.16
credentials:2.1.18
display-url-api:2.2.0
docker-commons:1.13
docker-slaves:1.0.7
docker-workflow:1.17
durable-task:1.25
git-client:2.7.3
git-server:1.7
git:3.9.1
jquery-detached:1.2.1
jsch:0.1.54.2
junit:1.24
ldap:1.20
mailer:1.21
matrix-project:1.13
pipeline-input-step:2.8
pipeline-model-api:1.3.1
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.3.1
pipeline-model-extensions:1.3.1
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.3.1
pipeline-utility-steps:2.1.0
plain-credentials:1.4
scm-api:2.2.7
script-security:1.44
ssh-credentials:1.14
structs:1.14
workflow-api:2.29
workflow-basic-steps:2.9
workflow-cps-global-lib:2.9
workflow-cps:2.54
workflow-durable-task-step:2.20
workflow-job:2.24
workflow-multibranch:2.20
workflow-scm-step:2.6
workflow-step-api:2.16
workflow-support:2.20
Cleaning up locks
Removing intermediate container 7dce95c12020
 ---> 0ea7017f9d1f
Step 5/5 : COPY jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml
 ---> d80b7f4704a2
Successfully built d80b7f4704a2
Successfully tagged jcasc_jenkins:latest
Creating jcasc_jenkins_1 ... done
Attaching to jcasc_jenkins_1
jenkins_1  | Running from: /usr/share/jenkins/jenkins.war
jenkins_1  | webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins_1  | Aug 13, 2018 1:48:10 PM org.eclipse.jetty.util.log.Log initialized
jenkins_1  | INFO: Logging initialized @221ms to org.eclipse.jetty.util.log.JavaUtilLog
jenkins_1  | Aug 13, 2018 1:48:10 PM winstone.Logger logInternal
jenkins_1  | INFO: Beginning extraction from war file
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.server.handler.ContextHandler setContextPath
jenkins_1  | WARNING: Empty contextPath
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.server.Server doStart
jenkins_1  | INFO: jetty-9.4.z-SNAPSHOT, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet
jenkins_1  | INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
jenkins_1  | INFO: DefaultSessionIdManager workerName=node0
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
jenkins_1  | INFO: No SessionScavenger set, using defaults
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.server.session.HouseKeeper startScavenging
jenkins_1  | INFO: Scavenging every 660000ms
jenkins_1  | Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.server.handler.ContextHandler doStart
jenkins_1  | INFO: Started w.@66971f6b{/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.server.AbstractConnector doStart
jenkins_1  | INFO: Started ServerConnector@770d0ea6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
jenkins_1  | Aug 13, 2018 1:48:11 PM org.eclipse.jetty.server.Server doStart
jenkins_1  | INFO: Started @1807ms
jenkins_1  | Aug 13, 2018 1:48:11 PM winstone.Logger logInternal
jenkins_1  | INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
jenkins_1  | Aug 13, 2018 1:48:12 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Started initialization
jenkins_1  | Aug 13, 2018 1:48:13 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Listed all plugins
jenkins_1  | Aug 13, 2018 1:48:16 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Prepared all plugins
jenkins_1  | Aug 13, 2018 1:48:16 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Started all plugins
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Augmented all extensions
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.InitReactorRunner$1 onTaskFailed
jenkins_1  | SEVERE: Failed ConfigurationAsCode.init
jenkins_1  | java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins_1  | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_1  | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  | Caused by: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins_1  | 	... 8 more
jenkins_1  | Caused by: java.lang.NullPointerException
jenkins_1  | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
jenkins_1  | 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
jenkins_1  | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
jenkins_1  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
jenkins_1  | 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
jenkins_1  | 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
jenkins_1  | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
jenkins_1  | 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:46)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:11)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:73)
jenkins_1  | 	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
jenkins_1  | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:73)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:12)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:73)
jenkins_1  | 	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
jenkins_1  | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:73)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:520)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:433)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:169)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:161)
jenkins_1  | 	... 13 more
jenkins_1  | 
jenkins_1  | Aug 13, 2018 1:48:17 PM hudson.util.BootFailure publish
jenkins_1  | SEVERE: Failed to initialize Jenkins
jenkins_1  | hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at hudson.WebAppMain$3.run(WebAppMain.java:250)
jenkins_1  | Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
jenkins_1  | 	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
jenkins_1  | 	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1102)
jenkins_1  | 	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
jenkins_1  | 	at hudson.model.Hudson.<init>(Hudson.java:85)
jenkins_1  | 	at hudson.model.Hudson.<init>(Hudson.java:81)
jenkins_1  | 	at hudson.WebAppMain$3.run(WebAppMain.java:233)
jenkins_1  | Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins_1  | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_1  | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  | Caused by: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins_1  | 	... 8 more
jenkins_1  | Caused by: java.lang.NullPointerException
jenkins_1  | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
jenkins_1  | 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
jenkins_1  | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
jenkins_1  | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
jenkins_1  | 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
jenkins_1  | 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
jenkins_1  | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
jenkins_1  | 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:46)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:11)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:73)
jenkins_1  | 	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
jenkins_1  | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:73)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:12)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:73)
jenkins_1  | 	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
jenkins_1  | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
jenkins_1  | 	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:73)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:520)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:433)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:169)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:161)
jenkins_1  | 	... 13 more
jenkins_1  | 
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.model.Jenkins cleanUp
jenkins_1  | INFO: Stopping Jenkins
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.model.Jenkins$19 onAttained
jenkins_1  | INFO: Started termination
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.model.Jenkins$19 onAttained
jenkins_1  | INFO: Completed termination
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.model.Jenkins _cleanUpDisconnectComputers
jenkins_1  | INFO: Starting node disconnection
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.model.Jenkins _cleanUpShutdownPluginManager
jenkins_1  | INFO: Stopping plugin manager
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.model.Jenkins _cleanUpPersistQueue
jenkins_1  | INFO: Persisting build queue
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.model.Jenkins _cleanUpAwaitDisconnects
jenkins_1  | INFO: Waiting for node disconnection completion
jenkins_1  | Aug 13, 2018 1:48:17 PM jenkins.model.Jenkins cleanUp
jenkins_1  | INFO: Jenkins stopped
```
