### ISSUE TITLE
Introduce integration test

### ISSUE THREAD

**Issue by tomasbjerre** [jenkinsci/configuration-as-code-plugin#489]
A quick look at the code tells me there are a lot of parts here that needs to fit together. How about introducing a simple integration test?

I scripted my setup when fiddling with this tool [here](https://github.com/tomasbjerre/docker-jenkins-sandbox).  So basically:
 * A jenkins.yaml with some realistic use case
 * A Dockerfile using that yaml
 * Shell script to clearly show how to run it

And preferably running it from the Jenkinsfile on PR:s.

**Comment by tomasbjerre** [comment]
Related to #257 but I think that sounds more like unit tests.

**Comment by ndeloof** [comment]
how would this differ from the existing integration tests which rely on JenkinsRule ?

**Comment by tomasbjerre** [comment]
Ok. Yes that is probably the way to go.

I had a look at the tests now and found that the only test case testing installation of plugins is disabled: https://github.com/jenkinsci/configuration-as-code-plugin/commit/4a8df85deb3d74ddafab58509b0e18f7844a4e04

Perhaps I should open a new issue on enabling plugin installation again? Because my YAML should be correct right?

```
jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git

plugins:
  required:
    generic-webhook-trigger: latest
    git-changelog: latest
    violation-comments-to-stash: latest
    violation-comments-to-gitlab: latest
    violation-comments-to-github: latest
```
