### ISSUE TITLE
FeatureRequest: provision initial users

### ISSUE THREAD

**Issue by metux** [jenkinsci/configuration-as-code-plugin#496]
I'd like to request support for provisioning initial users, with support for environment variables.
These should only be created if they're not existing, at least their password shouldn't be changed back to default if it already was changed.

**Comment by corburn** [comment]
@metux like this? I don't know if it will reset the password if the user exists.

```yaml
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "jane.doe"
          password: "12345"
```
