### ISSUE TITLE
Cannot modify slacknotifier plugin configuration

### ISSUE THREAD

**Issue by theomathieubhvr** [jenkinsci/configuration-as-code-plugin#505]
Hi, I'm still not sure how to configure slack plugin.

Any idea ?

```
unclassified:
  slacknotifier:
    teamDomain: "https://****.slack.com/services/hooks/jenkins-ci/"
    authTokenCredentialId: "slack_authtoken"
    baseUrl: "***"
```

I could add a working example on the repo.
