### ISSUE TITLE
Discover "delegation" in attributes management

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#51]
Some attributes are owned by `Jenkins` root class for legacy reasons but managed from a web UI point of view using `GlobalConfiguration` implementation (typically : security has a dedicated page).
We'd like to be able to discover this from the java codebase so we can mimic in the `yaml` model, so
```yaml
jenkins:
  securityRealm: ...
```

would become :
```yaml
jenkins:
  security:
     securityRealm:  ...
```
