### ISSUE TITLE
Exporting authorizationStrategy->globalMatrix->grantedPermissions differs from initial setup

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#519]
Comparing my initial casc.yaml file with the output generated via export, I found this irregularity:

Original:
```
jenkins:
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
[...]
      - "View/Delete:anonymous"
[...]
```
Export:
```
jenkins:
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
[...]
      - "Permission[class hudson.model.View,Delete]:anonymous"
[...]
```
