### ISSUE TITLE
Anonymous is missing the Overall/Administer permission

### ISSUE THREAD

**Issue by piomin** [jenkinsci/configuration-as-code-plugin#535]
I've got the following configuration file:
```
plugins:
  required:
    git: 3.9.1
    http_request: 1.8.22
    pipeline-model-definition: 1.3.2
    pipeline-stage-step: 2.3
    workflow-aggregator: 2.5
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "piomin"
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
```

After installing plugin on Docker container I've got the following error:

SEVERE: Failed to install Configuration as Code
java.io.IOException: Failed to dynamically deploy this plugin
at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1893)
at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:112)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to initialize configuration-as-code plugin
at hudson.PluginManager.dynamicLoad(PluginManager.java:902)
at hudson.PluginManager.dynamicLoad(PluginManager.java:823)
at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1889)
... 5 more
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
at hudson.PluginManager.dynamicLoad(PluginManager.java:900)
... 7 more
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
... 1 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
... 7 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class io.jenkins.plugins.casc.plugins.PluginManagerConfigurator configurator
at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:612)
at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:634)
at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:540)
at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:270)
at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:262)
... 12 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Failed to download plugin http_request:1.8.22
at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:202)
at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:93)
at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:58)
at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$configureWith$6(ConfigurationAsCode.java:634)
at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:606)
... 16 more
Caused by: hudson.security.AccessDeniedException2: anonymous is missing the Overall/Administer permission
at hudson.security.ACL.checkPermission(ACL.java:73)
at hudson.security.AccessControlled.checkPermission(AccessControlled.java:47)
at hudson.model.UpdateSite$Plugin.deploy(UpdateSite.java:1210)
at hudson.model.UpdateSite$Plugin.deploy(UpdateSite.java:1192)
at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:174)
... 20 more

I executed the following command to run Docker container with jenkins:lts

```
docker run -d --name jenkins-casc -p 8080:8080 -p 50000:50000 --env CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yml jenkins/jenkins:lts
```
