### ISSUE TITLE
Add ability to escape $ character in config file

### ISSUE THREAD

**Issue by angry-cellophane** [jenkinsci/configuration-as-code-plugin#577]
### Setup:
configuration-as-code plugin 1.0
jenkins 2.121.3

### Issue:
If a property's value has ${...} that doesn't refer to any secret but should be saved as it is, configuration as code plugin tries to resolve it as a secret, finds nothing and replaces with an empty value.

### Example
```yaml
  globallibraries:
    libraries:
    - defaultVersion: "master"
      name: "myLib"
      retriever:
        legacySCM:
          scm:
            git:
              branches:
              - name: "${library.myLib.version}"
```

Expected result:
```xml
<org.jenkinsci.plugins.workflow.libs.LibraryConfiguration>
      <name>myLib</name>
      <retriever class="org.jenkinsci.plugins.workflow.libs.SCMRetriever">
        <scm class="hudson.plugins.git.GitSCM" plugin="git@3.9.1">
          <branches>
            <hudson.plugins.git.BranchSpec>
              <name>${library.myLib.version}</name>
            </hudson.plugins.git.BranchSpec>
          </branches>
        </scm>
      </retriever>
    </org.jenkinsci.plugins.workflow.libs.LibraryConfiguration>
```

Actual result:
```xml
<org.jenkinsci.plugins.workflow.libs.LibraryConfiguration>
      <name>myLib</name>
      <retriever class="org.jenkinsci.plugins.workflow.libs.SCMRetriever">
        <scm class="hudson.plugins.git.GitSCM" plugin="git@3.9.1">
          <branches>
            <hudson.plugins.git.BranchSpec>
              <name>**</name>
            </hudson.plugins.git.BranchSpec>
          </branches>
        </scm>
      </retriever>
    </org.jenkinsci.plugins.workflow.libs.LibraryConfiguration>
```

As a workaround - put a space before the value, e.g. " ${...}"
```yaml
  globallibraries:
    libraries:
    - defaultVersion: "master"
      name: "myLib"
      retriever:
        legacySCM:
          scm:
            git:
              branches:
              - name: " ${library.myLib.version}"
```

from https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/casc/SecretSource.java
```java
 // TODO we probably will quickly reach some limits using regexp
    // Maybe we could adopt https://github.com/AndersDJohnson/brace-expansion-java or implement something comparable
    public static final Pattern SECRET_PATTERN = Pattern.compile("(?<!\\\\)\\$\\{([^:\\s]*)(?::-)?([^}\\s]*)?\\}");
```

If I get it right time to do the todo.
