### ISSUE TITLE
Unable to read initial secrets from Hashicorp Vault

### ISSUE THREAD

**Issue by AdamGoldsmith** [jenkinsci/configuration-as-code-plugin#611]
**Scenario**: We are building and configuring a Jenkins Master using JCasC via Ansible on a VM (not a container). Initial secrets are stored in Vault running in dev mode (this is non-production) on the same host. Manual secret retrieval has been tested successfully. Vault has been forced to use kv v1.

**Problem**: Unable to populate Jenkins credentials entry with a value from Vault even though Vault access variables are set in a file referenced by CASC_VAULT_FILE environment variable. The entry is created in the credentials, but it has an empty value which shows that JCasC is running OK, but it isn't getting the secret from Vault.

**Example snippet**:
```
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "secret-text"
              secret: ${TEST} #Load from Hashicorp Vault
              description: "Secret Text"
```
**Thoughts**: No way of confirming that the CASC_VAULT_FILE env var is being set correctly. Is there a correct way/process to follow for setting this environment variable when starting Jenkins via Ansible?
Can an operation be performed that checks JCasC can query Vault?
