### ISSUE TITLE
Yaml follows different formatting for credentials

### ISSUE THREAD

**Issue by ccactus** [jenkinsci/configuration-as-code-plugin#630]
When trying to use the credentials section of the plugin I ran in to a formatting issue. I use 2 spaces instead of tabs, but anything underneath credentials:system:domainCredentials:credentials require 4 spaces.

eg.
```
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "username"
              username: "some-user"
              password: "some-password" #Load from Environment Variable
              description: "Username/Password Credentials for some-user"
````
works, but 
```
credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
          scope: GLOBAL
          id: "username"
          username: "some-user"
          password: "some-password" #Load from Environment Variable
          description: "Username/Password Credentials for some-user"
```
does not.

- [2.138.2 ] Jenkins version
- [1.2 ] Plugin version
- [docker:jenkins/jenkins:lts 9cff19ad8c8b ] OS
