### ISSUE TITLE
Configuring retention strategy idle timeout causes exception

### ISSUE THREAD

**Issue by john-tipper** [jenkinsci/configuration-as-code-plugin#639]
When configuring the Docker Agent idle timeout using configuration as code with the following configuration under the docker template config section I get an exception

```
  clouds:
  - docker:
      containerCap: 5
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker"
      templates:
      - connector:
          attach:
            user: "jenkins"
        dockerTemplateBase:
          environmentsString: ""
          image: "jenkins/jnlp-slave"
          pullCredentialsId: "docker-registry"
          volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:Z"
          volumesString: "/var/run/docker.sock:/var/run/docker.sock:Z"
        remoteFs: ""
        labelString: "docker-slave"
        name: "docker-slave"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
        removeVolumes: true
        **retentionStrategy:
            dockerOnce:
              idleMinutes: 1**
```

I have tried to highlight the lines that cause the issue with `**`, but the `**` characters are quoted directly and mess up the indenting.  If you remove these lines, you don't get the exception.

The exception is:

```
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Cannot find configurator for type class io.jenkins.docker.DockerComputer
at io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry$1.load(DefaultConfiguratorRegistry.java:97)
```

I also see this exception when I try to export the configuration as code:

```
retentionStrategy: "FAILED TO EXPORT com.nirima.jenkins.plugins.docker.DockerTemplate#retentionStrategy:\
\ No configurator found for type class io.jenkins.docker.DockerComputer"
```

I queried this in the [Gitter channel](https://gitter.im/jenkinsci/configuration-as-code-plugin) and Nicolas De loof @ndeloof believes [https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/strategy/DockerOnceRetentionStrategy.java#L33](https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/strategy/DockerOnceRetentionStrategy.java#L33) is not identified as it should be.

Jenkins version: 2.149
CasC Plugin version: 1.3
Docker plugin: 1.1.5
OS: Jenkins docker image (jenkins:2.149-alpine)
