### ISSUE TITLE
Unable to set branchDiscoveryTrait on globalLibraries

### ISSUE THREAD

**Issue by mitchnielsen** [jenkinsci/configuration-as-code-plugin#657]
**Never report security issues in github, follow the instruction from [Jenkins Security](https://jenkins.io/security/) to report it on [Jenkins Jira](https://issues.jenkins-ci.org)**

Please make sure to provide following information in your issue description

- [x] Jenkins version: 2.138.1
- [x] Plugin version: 1.3
- [x] OS: CentOS 7.5

## Context

I'm _so close_ to being able to use this plugin in production for our team. The last piece missing is the **branchDiscoveryTrait** I'm trying to set on a global library.

## Code snippet

```
jenkins:
  [...]
unclassified:
  [...]
    globalLibraries:
    libraries:
      - name: <our repo name>
        defaultVersion: master
        implicit: true
        includeInChangeSets: true
        retriever:
          modernSCM:
            scm:
              github:
                apiUri: <our URL>
                credentialsId: <our creds>
                repoOwner: <our owner>
                repository: <our repo>
                traits:
                  - branchDiscoveryTrait # <--- issue right here
                  - originPullRequestDiscoveryTrait
                  - forkPullRequestDiscoveryTrait
```

## Logs

Here are the logs when starting Jenkins:

`INFO: Setting org.jenkinsci.plugins.github_branch_source.GitHubSCMSource{id='null'}.traits = [jenkins.plugins.git.traits.BranchDiscoveryTrait@3fb360b2, org.jenkinsci.plugins.github_branch_source.OriginPullRequestDiscoveryTrait@6b2b17b9, org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait@5938a4bb]`

## Result

originPullRequestDiscoveryTrait and forkPullRequestDiscoveryTrait are configured correctly, but branchDiscoveryTrait never appears. Note that applying the configuration does not result in an error/stack trace.

![image](https://user-images.githubusercontent.com/7725815/48807060-56f1f500-ecea-11e8-8588-be695ead392a.png)

Any help would be fantastic. Excited to have a modern, ____-as-code approach to managing Jenkins. Thank you!

**Comment by dgarzon** [comment]
@mitchnielsen I think this is related to my issue: https://github.com/jenkinsci/configuration-as-code-plugin/issues/658. Funny how both of us were working on the same thing today 👍

**Comment by mitchnielsen** [comment]
@dgarzon Glad to hear I’m not the only one!

**Comment by dougtweedy** [comment]
👍

**Comment by mitchnielsen** [comment]
When I try to export existing configuration after selecting the option with the UI, it still fails. Here's the config in jenkins.yml that I use:

```
...
traits:
- branchDiscoveryTrait:
    strategyId: 1
- originPullRequestDiscoveryTrait:
    strategyId: 1
- forkPullRequestDiscoveryTrait:
    strategyId: 1
```

And I get this error when loading the config:
```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class jenkins.plugins.git.traits.BranchDiscoveryTrait : strategyId.
Available attributes : 
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:363)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:352)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:262)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:81)
```
