### ISSUE TITLE
Add jobs in a view

### ISSUE THREAD

**Issue by CondormanFr** [jenkinsci/configuration-as-code-plugin#671]
Is there a way to add existing jobs inside a view in a jcasc file ?

```
 views:
  - list:
      name: "ViewName"
        jobNames:
            job: "Name of job1"
            job: "Name of job2"
...
```
