### ISSUE TITLE
githubpluginconfig's `hookUrl` not working?

### ISSUE THREAD

**Issue by acrewdson** [jenkinsci/configuration-as-code-plugin#672]
Hello,

First, thanks for this plugin. It's great to see that it's being widely adopted across the community. 

--------

* Jenkins version: 2.121.2
* jcasc plugin version: 1.3 (+ support plugin 1.3)
* `github` plugin version: 1.29.3
* CentOS 7

--------

The schema for `githubpluginconfig` looks like:

```json
{
  "org.jenkinsci.plugins.github.config.GitHubPluginConfig": {
    "type": "object",
    "properties": {
      "configs": {
        "type": "array",
        "items": {
          "type": "#/definitions/org.jenkinsci.plugins.github.config.GitHubServerConfig"
        }
      },
      "hookSecretConfig": {
        "type": "#/definitions/org.jenkinsci.plugins.github.config.HookSecretConfig"
      },
      "hookUrl": {
        "type": "#/definitions/java.net.URL"
      }
    }
  }
}
```

I have some configuration-as-code yaml that looks like:

```yaml
unclassified:
  githubpluginconfig:
    hookUrl: https://some-url/here
    configs:
      - name: Github.com
        apiUrl: https://api.github.com
        credentialsId: creds-id-here
        clientCacheSize: 20
        manageHooks: false
```

The `hookUrl` attribute does not seem to be expressed in the corresponding config XML file (we expect a `<hookUrl>` element). Is it possible the configuration-as-code plugin does not know how to map the `java.net.URL` type? Shouldn't that type technically be a `String`?

**Comment by jonbrohauge** [comment]
Surround the URL with quotes (") and try to see what happens.

**Comment by D4rkPa5senger** [comment]
I'm running into similar issue with logstash plugin. It requires type "java.net.URI" for elastisearch config and passing a string with quotes around it doesn't seem to help. Is there a specific way to pass URI/URL in yaml?

**Comment by jonbrohauge** [comment]
@acrewdson @D4rkPa5senger 
Checkout the example: <https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/github>

This is our config of the plugin, based on the example. It works...
```yaml
unclassified:
  githubpluginconfig:
    configs:
    - name: "[Name of our custom instance]"
      apiUrl: "[URL to our custom instance]/api/v3"
      credentialsId: "[Proper credentials]"
      manageHooks: true
```

**Comment by acrewdson** [comment]
@jonbrohauge That example (which I agree works) doesn't address the problem we're dealing with here, which has to do with `hookUrl`. Surrounding the URL with quotes also does not seem to have an effect.

Here's the YAML in question:

```yaml
unclassified:
  githubpluginconfig:
    hookUrl: "http://foo/bar"
    configs:
    - name: "InHouse GitHub EE"
      apiUrl: "https://github.domain.local/api/v3"
      credentialsId: "github-token-swiftype-ops"
      manageHooks: true
```

As you can see in this screen shot, `hookUrl` does not seem to work:
![hookurl2](https://user-images.githubusercontent.com/10353074/50347856-1366f280-0505-11e9-92c7-ff680d54c2ac.png)

Here's a screenshot from the JCasC 'reference' page on the Jenkins in question where `hookUrl` is shown:
![hookurl](https://user-images.githubusercontent.com/10353074/50347891-35f90b80-0505-11e9-950a-32f9d6712759.png)

**Comment by acrewdson** [comment]
@jonbrohauge That example (which I agree works) doesn't address the problem we're dealing with here, which has to do with `hookUrl`. Surrounding the URL with quotes also does not seem to have an effect.

Here's the YAML in question:

```yaml
unclassified:
  githubpluginconfig:
    hookUrl: "http://foo/bar"
    configs:
    - name: "InHouse GitHub EE"
      apiUrl: "https://github.domain.local/api/v3"
      credentialsId: "github-token-swiftype-ops"
      manageHooks: true
```

As you can see in this screen shot, `hookUrl` does not seem to work:
![hookurl2](https://user-images.githubusercontent.com/10353074/50348007-938d5800-0505-11e9-8b2e-ef795aae7616.png)

Here's a screenshot from the JCasC 'reference' page on the Jenkins in question where `hookUrl` is shown:
![hookurl](https://user-images.githubusercontent.com/10353074/50347891-35f90b80-0505-11e9-950a-32f9d6712759.png)

**Comment by acrewdson** [comment]
@jonbrohauge That example (which I agree works) doesn't address the problem we're dealing with here, which has to do with `hookUrl`. Surrounding the URL with quotes also does not seem to have an effect.

Here's the YAML in question:

```yaml
unclassified:
  githubpluginconfig:
    hookUrl: "http://foo/bar"
    configs:
    - name: "InHouse GitHub EE"
      apiUrl: "https://github.domain.local/api/v3"
      credentialsId: "...."
      manageHooks: true
```

As you can see in this screen shot, `hookUrl` does not seem to work:
![hookurl2](https://user-images.githubusercontent.com/10353074/50348007-938d5800-0505-11e9-8b2e-ef795aae7616.png)

Here's a screenshot from the JCasC 'reference' page on the Jenkins in question where `hookUrl` is shown:
![hookurl](https://user-images.githubusercontent.com/10353074/50347891-35f90b80-0505-11e9-950a-32f9d6712759.png)
