### ISSUE TITLE
Unable to set e-mail notification credentials

### ISSUE THREAD

**Issue by damlys** [jenkinsci/configuration-as-code-plugin#679]
There is no possibility to set mailer credentials "as code". JCasC handles `smtpHost`, `smtpPort` and `useSsl` fields, but it doesn't handle `useSMTPAuth`, `smtpAuthUserName` and `smtpAuthPasswordSecret` fields.

##### Expected result

JCasC plugin should handle `useSMTPAuth`, `smtpAuthUserName` and `smtpAuthPasswordSecret` fields.

##### Example configuration

```
unclassified:
  mailer:
    adminAddress: admin <admin@dummy.tld>
    replyToAddress: admin <admin@dummy.tld>
    charset: UTF-8

    smtpHost: smtp.mailgun.org
    smtpPort: 587
    useSsl: false

    useSMTPAuth: true
    smtpAuthUserName: XXXXX@XXXXX.mailgun.org
    smtpAuthPasswordSecret: XXXXX
```

##### Tested with following stack

- Jenkins version: 2.152
- JCasC plugin version: 1.3
- `mailer` plugin: 1.22
- OS: Linux
