### ISSUE TITLE
[Feature] Plugin installation

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#7]
If we install new plugins in the plugin.yml file, how can they be updated without restart as many plugins require restart on update.

**Comment by ndeloof** [comment]
I don't expect configuration-as-code to fix all jenkins design issues :-P
configuration-as-code could easily _check_ a required list of plugin is installed, as some sort of a company policy check. But installing plugins is a distinct job, which require a restart in most cases, and also hardly can be managed by this plugin from _inside_ jenkins, would need to run priori to it's execution. Better imho to rely on plugins.txt as in docker image.

**Comment by ndeloof** [comment]
My current thoughts on this feature:

We could implement a dedicated Configurator for a new `plugins` RootElement and related new management component.

- relies on a map of plugin ID -> version
```yaml
plugins:
  git: 2.4
  maven: 1.2
```
- checks PluginManager for installed plugins and compare with required version. 
- react on version mismatch or plugin failure by replacing stapler `app` with an error page to block startup (or System.exit ?). 

If we want to offer an equivalent for docker image's [install-plugins.sh](https://github.com/jenkinsci/docker/blob/master/install-plugins.sh) script we will need one additional step :

- react on missing plugins by triggering installation and restart jenkins. 

But this would have to run _after_  `jenkins.updateCenter.sites` and `jenkins.proxy`, have been configured, and also the yaml configuration would probably be invalid at parsing time as referenced plugins aren't installed yet (chicken and egg issue).

So we will need to have a special configuration file loaded before all others, to set `jenkins.updateCenter.sites`, `jenkins.proxy`, and required plugins, then (maybe after restart) parse other configuration files.
As `jenkins.proxy` is configured on UI via PluginManager, I suggest we define a special role for a `plugins.yaml` file to be loaded first and used to configure PluginManager (and only this guy) :

```yaml
plugins: # alias for PluginManager
  updateSites:
    - "http://jenkins-uc.acme.com"
  proxy:
    name: "proxy.acme.com"
    port: 8080
    userName: foo
    password: ${INJECT}
  required:
    git: 2.4
    maven: 1.2
```
