### ISSUE TITLE
Kubernetes Containers Command args ignored in v1.5

### ISSUE THREAD

**Issue by ssc327** [jenkinsci/configuration-as-code-plugin#737]
Jenkins version: 2.121.3
Plugin version: 1.5
OS: RHEL

I am using K8's to provision slaves for Jenkins and I define my slaves in JCasC. An example config is below:

```
 - kubernetes:
      addMasterProxyEnvVars: true
      containerCapStr: "100"
      ...
      templates:
      - containers:
        - alwaysPullImage: true
          args: "${computer.jnlpmac} ${computer.name}"
          command: ""

```
I set **command** to be an empty String because otherwise it is defaulted to something like /bin/sh cat and that results in my agents dying.

In version 1.4, the above config works perfectly fine but when I upgrade to 1.5, the empty string for command is ignored and /bin/sh is set and thus my agents all fail.
