### ISSUE TITLE
Update Active Directory "tlsConfiguration" for v1.5 +

### ISSUE THREAD

**Issue by h1dden-da3m0n** [jenkinsci/configuration-as-code-plugin#740]
# Description

Greetings again,
So I updated one of our test Jenkins instances with the latest plugin versions, was actually trying to test something else, and noticed that CasC all of the sudden gave me a warning.
Said warning referred to the configuration containing the setup for the Active Directory plugin and complained that the `tlsConfiguration` option was no valid CasC option, this seemed quite odd as:

1.  it’s in the official CasC [examples](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/active-directory/README.md) and used to work with v1.4 (running in the other instances)
2. it’s in one of the [test yamls](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/src/test/resources/io/jenkins/plugins/casc/ActiveDirectoryTest.yml) and 
3. the AD plugin itself still uses the option and if not set via CasC uses its default *"(Unsecure) Trust all Certificates"*

After a bit of investigation and comparing the test instance with one of our prod instances I found that, the new Active Directory plugin moved the `tlsConfiguration` from the global level to a domain level.
Given that discovery I tried to move the option to the domain level in my CasC yaml and it worked again.

So what all I want to report is a somewhat misleading example and test YAML (that can be found here on GH) and a not very helpful CasC docu as it simply states `domains --- list ofActiveDirectoryDomain` with no further link to the structure of `ofActiveDirectoryDomain`.

Anyway, Thanks of the read, hopefully update of the example and in general for THIS AWSOME Project. 👍 

(ps.: sorry if this was an already knowen "issue" but i dint find any issues concerning this)

# Error Message
![image](https://user-images.githubusercontent.com/33120068/53001060-15c4ca80-342a-11e9-81d0-654ddb25933d.png)

# Used CasC Yaml (valid for CasC 1.4 & AD 2.10)
```yaml
jenkins:
  securityRealm:
    activeDirectory:
      groupLookupStrategy: RECURSIVE
      startTls: true
      tlsConfiguration: JDK_TRUSTSTORE
      domains:
      - name: "<retracted url>"
```

# Used CasC Yaml (valid for CasC 1.5+ & AD 2.12+)
```yaml
jenkins:
  securityRealm:
    activeDirectory:
      groupLookupStrategy: RECURSIVE
      startTls: true
      domains:
      - name: "<retracted url>"
        tlsConfiguration: JDK_TRUSTSTORE
```

# Environment

- [2.150.2] Jenkins version
- [1.5] CasC version
- [2.12] Active Directory plugin version
- [debian 9] OS (Docker container base)
