### ISSUE TITLE
Kubernetes service account credential example

### ISSUE THREAD

**Issue by aramse** [jenkinsci/configuration-as-code-plugin#745]
Please provide an example for a Kubernetes service account credential, basically the credential that would be referred to by **advanced-k8s-credentials** on this line: https://github.com/jenkinsci/configuration-as-code-plugin/blob/4faf0c0b5a6154fc04366aa83572acdd1f70cf49/demos/kubernetes/adv_config.yml#L19

**Comment by casz** [comment]
There are several examples of how to create credentials.
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/credentials
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/credentials/credentials.yaml

**Comment by aramse** [comment]
There are no examples of creating one for a **Kubernetes service account**, like in the quoted line I supplied. Currently I have to create it manually.

**Comment by casz** [comment]
Have you even bothered to attempt to use the export or looked at the reference document available at http://<SERVER_URL>/configuration-as-code/reference ?

Just because there is no documentation in this repo, does not mean it is not possible. There are too many plugins to keep an example of every single one.

Looking at the code: https://github.com/jenkinsci/kubernetes-credentials-plugin/blob/master/src/main/java/org/jenkinsci/plugins/kubernetes/credentials/FileSystemServiceAccountCredential.java
It should be possible since it is databound with a descriptor.

If you went ahead and manually created it, you should also be able to manually export it.

**Comment by casz** [comment]
The code excepts a file to available at this path: /var/run/secrets/kubernetes.io/serviceaccount/token

So all you had to do in JCasC is to take the class name and give it a scope, id and description and presto.

```yaml
credentials:
  system:
    domainCredentials:
      - credentials:
          - fileSystemServiceAccountCredential:
              scope: SYSTEM
              id: kubernetes_service_account
              description: "Kubernetes service account"
```
