### ISSUE TITLE
Use Spot Instance

### ISSUE THREAD

**Issue by Kopei** [jenkinsci/configuration-as-code-plugin#762]
Hi, Does this plugin support on spot EC2 configuration setup?  search around, but not found it.

Please make sure to provide following information in your issue description

- [2.150] Jenkins version
- [1.7] Plugin version
- [Centos7 ] OS
- [1.42] EC2 plugin

**Comment by casz** [comment]
The answer is to go find out, the usual answer is yes if the plugin follows https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md

I'd say try to install JCasC and see what you can see in the schema, located: https://your.jenkinsurl.dot/configuration-as-code/reference

**Comment by Kopei** [comment]
can work like this, thx!
```yaml
jenkins:
  clouds:
  - amazonEC2:
      cloudName: "ec2-agents"
      credentialsId: "jenkins-aws"
      privateKey: "${EC2_PRIVATE_KEY}"
      region: "ap-southeast-1"
      templates:
      - ami: "ami-04c4518821aad93f7"
        amiType:
          unixData:
            sshPort: "22"
        associatePublicIp: true
        connectBySSHProcess: true
        connectUsingPublicIp: true
        deleteRootOnTermination: true
        description: "ec2 slave"
        ebsOptimized: false
        idleTerminationMinutes: "2"
        labelString: "ec2 linux"
        mode: NORMAL
        monitoring: false
        numExecutors: 2
        remoteAdmin: "ec2-user"
        securityGroups: "sg-b01bcccb"
        stopOnTerminate: false
        type: T2Micro
        useDedicatedTenancy: false
        useEphemeralDevices: false
        usePrivateDnsName: false
        subnetId: "subnet-0a2de053"
        spotConfig:
          spotMaxBidPrice: "0.009"
      useInstanceProfileForCredentials: false
      instanceCapStr: "2"
      roleArn: ""
      roleSessionName: ""
```
