### ISSUE TITLE
authorizationStrategy: unsecured still wants me to create an admin user

### ISSUE THREAD

**Issue by dmolesUC3** [jenkinsci/configuration-as-code-plugin#773]
I'm running a throwaway instance of Jenkins in a Docker container on a machine that's only accessible to people who in principle would all have admin privileges anyway.

I've tried copying the configuration from [`UnsecuredAuthorizationStrategyConfiguratorTest.yml`](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/test/resources/io/jenkins/plugins/casc/core/UnsecuredAuthorizationStrategyConfiguratorTest.yml), but when I navigate to Jenkins the first thing I get is a prompt to create an admin user. Full `jenkins.yaml`:

```
plugins:
  required:
    blueocean: 1.13.1
    configuration-as-code: 1.7

jenkins:
  systemMessage: |
    Jenkins Docker image built from https://github.com/dmolesUC3/mrt-jenkins-docker
  mode: NORMAL
  numExecutors: 2
  scmCheckoutRetryCount: 2
  securityRealm:
    local:
      allowsSignup: false
  authorizationStrategy: unsecured
```

I tried

```
  securityRealm: none
```

but that just got me

```
java.lang.IllegalArgumentException: No hudson.security.SecurityRealm implementation found for none
Possible solution: Try to install 'configuration-as-code-support' plugin
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.findDescribableBySymbol(HeteroDescribableConfigurator.java:148)
```

What am I missing?

## System information

- Jenkins 2.150.3 (`jenkins/jenkins:lts` Docker image)
- configuration-as-code version 1.7
- macOS (as Docker host)

**Comment by dmolesUC3** [comment]
After creating an admin user, I did a configuration export, and based on that I changed my config to:

```
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: admin
          password: admin
  authorizationStrategy: unsecured
```

This kind-of-sort-of worked insofar as it didn't require me to create an admin user when I navigated to Jenkins; however, instead I was presented with the setup wizard. Exiting the setup wizard (with ❌) instead of selecting plugins got me:

> # Jenkins is ready!
>
> You have skipped the setup of an admin user. 
> 
> To log in, use the username: "admin" and the administrator password you used to access the setup wizard.
> You have skipped the configuration of the Jenkins URL. 
> 
> To configure the Jenkins URL, go to "Manage Jenkins" page.
> Your Jenkins setup is complete.

This manages to be marginally more annoying than having to create a user.
