### ISSUE TITLE
Embedded user database can't be set with multiple users

### ISSUE THREAD

**Issue by dburm** [jenkinsci/configuration-as-code-plugin#820]
- Jenkins 2.150.3
- JCasC 1.10
- Mint 19
- openjdk-8-jdk 8u181-b13-2~deb9u1

Config section
```
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
        - id: "jenkins"
```
raises an exception

> userWithPassword: Failed to set attribute users(class: class io.jenkins.plugins.casc.core.HudsonPrivateSecurityRealmConfigurator$UserWithPassword, multiple: true)
> java.lang.NullPointerException
> 	at io.jenkins.plugins.casc.core.HudsonPrivateSecurityRealmConfigurator.setter(HudsonPrivateSecurityRealmConfigurator.java:57)
> 	at io.jenkins.plugins.casc.Attribute.setValue(Attribute.java:169)
> 	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:353)
> Caused: io.jenkins.plugins.casc.ConfiguratorException: userWithPassword: Failed to set attribute users(class: class io.jenkins.plugins.casc.core.HudsonPrivateSecurityRealmConfigurator$UserWithPassword, multiple: true)

**Comment by timja** [comment]
Looks like its getting a null pointer on password, not the fact there's multiple users

Example config:
https://github.com/hmcts/cnp-jenkins-config/blob/master/cac-test.yml#L75-L77

Is it valid to set with no password?

**Comment by timja** [comment]
Also the demo config has password in it:
https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/embedded-userdatabase

**Comment by dburm** [comment]
Yeah, looks as invalid. Previously installed version of JCasC probably ignores missed password field.

**Comment by hilafish1** [comment]
Sorry to bring it out of the pit, but.. I run into this as well-
```
  JCasC:
    jenkins:          
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "Jenkins Admin"
            password: "${chart-admin-password}"
          - id: "ml-admin"
            name: "ML Admin"
            password: "Passw0rd"    
```

First user was created, the second doesn't. Nothing on the log.
I'm using the latest chart, jenkins and configuration-as-code plugin versions.
@dburm, @timja Any pointers?

**Comment by hilafish** [comment]
Sorry to bring it out of the pit, but.. I run into this as well-
```
  JCasC:
    jenkins:          
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "Jenkins Admin"
            password: "${chart-admin-password}"
          - id: "ml-admin"
            name: "ML Admin"
            password: "Passw0rd"    
```

First user was created, the second doesn't. Nothing on the log.
I'm using the latest chart, jenkins and configuration-as-code plugin versions.
@dburm, @timja Any pointers?
