### ISSUE TITLE
Vault usage explanation

### ISSUE THREAD

**Issue by awolde** [jenkinsci/configuration-as-code-plugin#821]
### Description
I am trying to use Vault to read secrets from. I have a chart yaml file that looks like this 
```jenkins:
  Master:
    ContainerEnv:
      - name: CASC_VAULT_TOKEN
        value: "some-auth-token"
      - name: CASC_VAULT_URL
        value: "http://10.180.0.1:8200"
      - name: CASC_VAULT_PATHS
        value: "database/creds/pgsql_role"
```
I generated the CASC_VAULT_TOKEN with `vault token create -policy=token-policy -use-limit=10`, and that policy has read access to the `database/creds/pgsql_role` path.
My problem is how to read the secrets from vault after spinning up Jenkins. Do I use certain env variables? Basically I want Jenkins to do `vault read database/creds/pgsql_role` and use the username and password generated. It seems the documentation is talking about using Docker secrets but does not give specific examples. Any help would be appreciated.

**Comment by casz** [comment]
any secrets on that path will be available as key-value pairs.

So use the key you use the name of the key like so `${VSPHERE_USERNAME}` or `${VSPHERE_USERNAME:-DefaultNotAUser}`

All of it is covered by https://github.com/jenkinsci/configuration-as-code-plugin#handling-secrets

Secrets are taken care of in a generic way, and we support multiple data sources. Vault is just one of 3 current secret sources supported by the JCasC main plugin.
Other are available such as https://github.com/jenkinsci/configuration-as-code-secret-ssm-plugin

![image](https://user-images.githubusercontent.com/1661688/55583688-ce1ca880-5722-11e9-8217-aca4db35024c.png)

**Comment by awolde** [comment]
I'm using Jcasc to setup Jenkins, and Jenkins is not running yet. I want to use stored passwords from Vault when initializing Jenkins.
This is the response I get from Vault. 
```curl -s --header "X-Vault-Token: myyytoken" $VAULT_ADDR/v1/database/creds/pgsql_role | jq
{
  "request_id": "38a3b3bf-bda2-becd-ff73-ddccd3a4f64e",
  "lease_id": "database/creds/pgsql_role/S5wDnFJ2S19EHk7",
  "renewable": true,
  "lease_duration": 3600,
  "data": {
    "password": "QdAuuc47P4",
    "username": "7DlBLSihGom4n5tHWx-1554411702"
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}```

**Comment by casz** [comment]
What you want is entirely possible, so I am not sure what your issue is.
JCasC on startup should detect your vault environment variables and automatically connect and retrieve the secrets. Exposing them to the JCasC context and allow you to use those in the configure step when configuring the YAML sources specified in the `CASC_JENKINS_CONFIG`

**Comment by awolde** [comment]
I dont know what type of syntax that I should use. Here is my values.yaml file. Does it look correct to you? @casz 
```
Master:
    ContainerEnv:
      - name: CASC_VAULT_TOKEN
        value: "s.9VZ5paLnG2RO"
      - name: CASC_VAULT_URL
        value: "http://10.180.0.1:8200"
      - name: CASC_VAULT_PATHS
        value: "cubbyhole/jenkins"
    JCasC:
      enabled: true
      PluginVersion: 1.5
      SupportPluginVersion: 1.5
      ConfigScripts:
        ad-settings: |
          jenkins:
            securityRealm:
              activeDirectory:
                bindPassword: ${BINDPASSWORD}
                customDomain: true
                domains:
                - bindName: "CN=admin,dc=example,dc=org"
                  bindPassword: ${BINDPASSWORD}
                  name: "example.com"
                  servers: "dc1.example.com:389"
                  tlsConfiguration: TRUST_ALL_CERTIFICATES
                groupLookupStrategy: AUTO
                removeIrrelevantGroups: false
                startTls: true
```

And here is my secret in vault
```
curl -s --header "X-Vault-Token: s.9VZ5paLnG2RO" http://10.180.0.1:8200/v1/cubbyhole/jenkins  | jq
{
  "request_id": "a43d6fc9-dc-e546d2d3d2c0",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "BINDPASSWORD": "my-bind-password"
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

**Comment by casz** [comment]
You need to quote when using secrets so `bindPassword: "${BINDPASSWORD}"`

**Comment by awolde** [comment]
Did that and here's what I get next in the container when it starts
```
WARNING: Unable to fetch secret from Vault
com.bettercloud.vault.VaultException: Vault responded with HTTP status code: 404
Response body: {"errors":[]}

	at com.bettercloud.vault.api.Logical.read(Logical.java:98)
	at com.bettercloud.vault.api.Logical.read(Logical.java:74)
	at io.jenkins.plugins.casc.impl.secrets.VaultSecretSource.readSecretsFromVault(VaultSecretSource.java:152)
	at io.jenkins.plugins.casc.impl.secrets.VaultSecretSource.init(VaultSecretSource.java:216)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:634)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:531)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:274)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Whereas I can get the secrets via `curl -s --header "X-Vault-Token: s.9VZ5paLnG2RO" http://10.180.0.1:8200/v1/cubbyhole/jenkins` on the pod with no problem.

**Comment by casz** [comment]
Please configure `CASC_VAULT_ENGINE_VERSION` accordingly. I assume your cubbyhole is a v1 KV engine so `CASC_VAULT_ENGINE_VERSION=1`

https://github.com/jenkinsci/configuration-as-code-plugin#vault

**Comment by awolde** [comment]
Awesome, works! My assumption was the /var/jenkins_config/ad-settings.yaml file will have the secret in plain text, but thats not the case. It seems Jcasc handles that with master key encryption. Nice.

**Comment by casz** [comment]
Working as intended :sweat_smile:

**Comment by dhs-rec** [comment]
I wonder why this ticket has been closed w/o improving the documentation (as requested). I also need to find this ticket to really understand how things work. Please reopen and fix the docs.

**Comment by alan-mas** [comment]
Hi!
I just found this thread and it has been pretty helpfull for me, but I do still do not find a solution of my issue (in case adding a comment in a close issue is wrong, please feel free to delete my comment).

CONTEXT:
I am triying to deploy a Jenkins using helm with JCASC to get vault secrets. I am using a local `minikube` to create mi `k8` cluster and a local `vault` instance in my machine (not in k8 cluster) 

Even that I am trying using `initContainerEnv` and `ContainerEnv` I am not able to reach the vault values here is my .`yml` code:

```
controller:
  installPlugins:
    # need to add this configuration-as-code due to a known jenkins issue: https://github.com/jenkinsci/helm-charts/issues/595
  - "configuration-as-code:1414.v878271fc496f"
  - "hashicorp-vault-plugin:latest"

  # passing initial environments values to docker basic container
  initContainerEnv:
  - name: CASC_VAULT_TOKEN
    value: "some-token"
  - name: CASC_VAULT_URL
    value: "http://localhost:8200"
  - name: CASC_VAULT_PATHS
    value: "cubbyhole/jenkins"
  - name: CASC_VAULT_ENGINE_VERSION
    value: "2"
  ContainerEnv:
  - name: CASC_VAULT_TOKEN
    value: "some-token"
  - name: CASC_VAULT_URL
    value: "http://localhost:8200"
  - name: CASC_VAULT_PATHS
    value: "cubbyhole/jenkins"
  - name: CASC_VAULT_ENGINE_VERSION
    value: "2"

  JCasC:
    configScripts:
      here-is-the-user-security: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
                - id: "${JENKINS_ADMIN_ID}"
                  password: "${JENKINS_ADMIN_PASSWORD}"
```
Any of you have an idea what I could be doing wrong?
