### ISSUE TITLE
Credentials problem during jenkins.yaml importation

### ISSUE THREAD

**Issue by BlackJam44** [jenkinsci/configuration-as-code-plugin#933]
### Environment
- Jenkins version 2.176.1
- Plugin version: 1.21
- OS : VM Windows Server 2019 Standard - 64 bit

### Description
I'm writing my first Jenkins CasC configuration file. When I try to apply it, I've got the following error message and I don't understand how to resolve it : 

```
Item isn't a Sequence

io.jenkins.plugins.casc.ConfiguratorException: Item isn't a Sequence

	at io.jenkins.plugins.casc.model.CNode.asSequence(CNode.java:22)

	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:342)

	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)

	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:353)

	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)

	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:672)

	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:634)

Caused: io.jenkins.plugins.casc.ConfiguratorException: credentials: error configuring 'credentials' with class com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator configurator
```

### jenkins.yaml credential part
I put directly the passwords value as strings
```
# Credentials used by Jenkins and by jenkins projects       
credentials:
  system:
    domainCredentials:
      credentials:
        - usernamePassword:
          scope: GLOBAL
          id: "username1"
          username: 'username1'
          password: "password1"
          description: "RD"
        - usernamePassword:
          scope: GLOBAL
          id: "username2"
          username: 'username2'
          password: "password2"
          description:
        - usernamePassword:
          scope: GLOBAL
          id: "username3"
          username: 'username3'
          password: "password3"
          description: "gitlab RD user"
```

**Comment by timja** [comment]
I think this should be:
```
        - usernamePassword:
            scope: GLOBAL
            id: "username1"
            username: 'username1'
            password: "password1"
            description: "RD"
```

**Comment by BlackJam44** [comment]
You're write about the indentation. I corrected it but it doesn't fix the problem.

**Comment by jansohn** [comment]
Try it without the empty `description` element.

**Comment by BlackJam44** [comment]
Done, but error is still there

**Comment by casz** [comment]
Credentials are a bit funky on indenting

```
credentials:
  system:
    domainCredentials:
      # global credentials
      - credentials: 
      # must be 4 spaced after this point
          - usernamePassword:
              scope: GLOBAL
              id: artifactory
              username: "${ARTIFACTORY_USERNAME}"
              password: "${ARTIFACTORY_PASSWORD}"
          - usernamePassword:
              scope: GLOBAL
              id: vsphere
              username: "${VSPHERE_USERNAME}"
              password: "${VSPHERE_PASSWORD}"
          - usernamePassword:
              scope: GLOBAL
              id: jenkins_devops
              username: "${JENKINS_DEVOPS_USERNAME}"
              password: "${JENKINS_DEVOPS_APITOKEN}"
              description: Automated administrative tasks in Jenkins
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: gitlab_ssh_key
              username: git
              description: SSH key for GitLab
              privateKeySource:
                directEntry:
                  privateKey: "${SSH_PRIVATE_KEY}"
          - GitLabApiTokenImpl:
              scope: GLOBAL
              id: gitlab_token
              apiToken: "${GITLAB_TOKEN}"
              description: Gitlab Token
          - string:
              scope: GLOBAL
              id: slack-token
              secret: "${SLACK_TOKEN}"
              description: Slack token
          - usernamePassword:
              scope: GLOBAL
              id: "gitlabrunner"
              description: "gitlab runner"
              username: "gitlab-runner"
              password: "${GITLABRUNNER_PASSWORD}"
          - vaultAppRoleCredential:
              scope: GLOBAL
              id: "jenkins-build-approle-secret"
              description: "jenkins-build-approle-secret"
              roleId: "${BUILD_APPROLE_ID}"
              secretId: "${BUILD_APPROLE_SECRET_ID}"
```
