### ISSUE TITLE
casc globalMatrix for Attributes: LockableResources and JobImportAction

### ISSUE THREAD

**Issue by Harguer** [jenkinsci/configuration-as-code-plugin#942]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

Describe your feature request here.
Hello
I have all the globalMatrix/grantedPermissions attributes configured on my values.yaml, except for three that I cant find. By any chance are these attributes exist for jcasc?

these are the attributes showed inside the config.xml file (i got it clicking manually from the web-gui, it regenerate the config.xml)

 ```
<permission>org.jenkins.ci.plugins.jobimport.JobImportAction.JobImport:group_jenkins</permission>$
 <permission>org.jenkins.plugins.lockableresources.LockableResourcesManager.Reserve:group_jenkins</permission>$
 <permission>org.jenkins.plugins.lockableresources.LockableResourcesManager.Unlock:group_jenkins</permission>$
```

this is how looks my authorizationStrategy section into my values.yaml 

```
          authorizationStrategy:
            globalMatrix:
              grantedPermissions:
                - "View/Delete:group_jenkins"
                - "View/Read:group_jenkins"
                - "View/Configure:group_jenkins"
                - "View/Create:group_jenkins"
                - "Credentials/Create:group_jenkins"
                - "Credentials/Delete:group_jenkins"
                - "Credentials/ManageDomains:group_jenkins"
                - "Credentials/Update:group_jenkins"
                - "Credentials/View:group_jenkins"
                - "Agent/Connect:group_jenkins"
                - "Agent/Disconnect:group_jenkins"
                - "Agent/Configure:group_jenkins"
                - "Agent/Create:group_jenkins"
                - "Agent/Delete:group_jenkins"
                - "Agent/Build:group_jenkins"
                - "Artifactory/Promote:group_jenkins"
                - "Artifactory/Release:group_jenkins"
                - "Job/Read:group_jenkins"
                - "Job/Build:group_jenkins"
                - "Job/Configure:group_jenkins"
                - "Job/Create:group_jenkins"
                - "Job/Delete:group_jenkins"
                - "Job/Discover:group_jenkins"
                - "Job/Move:group_jenkins"
                - "Job/Workspace:group_jenkins"
                - "Job/Cancel:group_jenkins"
                #- "LockableResourcesManager/Reserve:group_jenkins"
                #- "LockableResourcesManager/Unlock:group_jenkins"
                #- "JobImportAction/JobImport:group_jenkins"
                - "Run/Delete:group_jenkins"
                - "Run/Replay:group_jenkins"
                - "Run/Update:group_jenkins"
                - "SCM/Tag:group_jenkins"
                - "Overall/Read:group_jenkins_readonly"
                - "Overall/Administer:group_jenkins"
                - "Overall/Read:group_jenkins"
```
