### ISSUE TITLE
Add the ability to write directly to file system

### ISSUE THREAD

**Issue by nocode99** [jenkinsci/configuration-as-code-plugin#954]
### Feature Request

Using the CasC yaml file to write files to Jenkins file system.

```yaml
files:
  - file:
      path: ${JENKINS_HOME}/some_file
      mode: 0755
      owner: jenkins
      group: jenkins
      contents: >
        hello, world
   - file:
       path: ....
```

Perhaps this is a terrible use case, but some of our jobs rely on having an SSH key available.  I'd love to be able to leverage CasC/Vault to get an SSH key and add it to the file system with the appropriate permissions.  We have a job that uses submodules and even though we configure the authentication in the Git settings, git is somehow not honoring the credentials used to pull the remote repository.

For now, I have configured another job to do this for me, but I don't see any other option.  I certainly don't want to push this ssh key in my docker build.
