### ISSUE TITLE
Could not pass argument for kubernetes

### ISSUE THREAD

**Issue by carlosjer** [jenkinsci/configuration-as-code-plugin#960]
### Your checklist for this issue

🚨 Please review the [Support Policy](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md)

- [x] The question was asked in the project's [Gitter chat](https://gitter.im/jenkinsci/configuration-as-code-plugin)
- [ ] Jenkins version
- [ ] Plugin version
- [ ] OS
- [ ] Reproduction steps

### Description
I tried adding `^` but for some reason it's not being accepted as an escape for `${computer.jnlpmac} ${computer.name}`. I'm getting an error where it looks for the AWS credentials. I tried putting the caret in between `$` and `{` and the file got thru but I get `$^{computer.jnlpmac} $^{computer.name}` which is not what needs to appear in args in kubernetes.

**Comment by timja** [comment]
It doesn't say what you tried initially?
have you tried:
```
^${computer.jnlpmac}
```
or
```
"^${computer.jnlpmac}"
```

**Comment by carlosjer** [comment]
yes. I have tried both `^${computer.jnlpmac}` and `"^${computer.jnlpmac}" ` but they still check for AWS credentials.

![image](https://user-images.githubusercontent.com/43393612/61694783-c7af4c80-ad64-11e9-9a58-4a5fffc59b77.png)

**Comment by casz** [comment]
@carlosjer a snippet of your yaml config would be helpful 😓

**Comment by carlosjer** [comment]
Apologies. here is the snippet of the yaml config I am using. The error above is the result I get for using `args: "^${computer.jnlpmac} ^${computer.name}"`

```
jenkins:
  systemMessage: "Testing kubernettes"
  clouds:
  - kubernetes:
      name: "kubernetes"
      serverUrl: "https://kubernetes.default"
      namespace: "jx"
      jenkinsUrl: "http://jenkins:8080"
      containerCapStr: "0"
      maxRequestsPerHostStr: "32"
      jenkinsTunnel: "jenkins-agent:50000"                        
      templates:
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          command: " "
          image: "jenkinsci/jnlp-slave:3.26-1-alpine"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          resourceRequestCpu: "100m"
          resourceRequestMemory: "128Mi"
        - args: "cat"
          command: "/bin/sh -c"
          image: "gcr.io/jenkinsxio/builder-maven-nodejs:0.1.464"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "aws-cdk"
          privileged: true
          resourceLimitCpu: "2"
          resourceLimitMemory: "2048Mi"
          resourceRequestCpu: "400m"
          resourceRequestMemory: "512Mi"
          ttyEnabled: true
        envVars:
        - containerEnvVar:
            key: "DOCKER_CONFIG"
            value: "/home/jenkins/.docker/"
        - containerEnvVar:
            key: "GIT_AUTHOR_EMAIL"
            value: "jenkins-x@googlegroups.com"
        - containerEnvVar:
            key: "GIT_AUTHOR_NAME"
            value: "jenkins-x-bot"
        - containerEnvVar:
            key: "GIT_COMMITTER_EMAIL"
            value: "jenkins-x@googlegroups.com"
        - containerEnvVar:
            key: "GIT_COMMITTER_NAME"
            value: "jenkins-x-bot"
        - containerEnvVar:
            key: "JENKINS_URL"
            value: "http://jenkins:8080"
        - containerEnvVar:
            key: "XDG_CONFIG_HOME"
            value: "/home/jenkins"
        - containerEnvVar:
            key: "_JAVA_OPTIONS"
            value: "-XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true\
              \ -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10\
              \ -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx512m"
        label: "jenkins-aws-cdk"
        name: "aws-cdk"
        nodeUsageMode: "NORMAL"
        serviceAccount: "jenkins"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        - secretVolume:
            mountPath: "/root/.m2/"
            secretName: "jenkins-maven-settings"
        - secretVolume:
            mountPath: "/home/jenkins/.docker"
            secretName: "jenkins-docker-cfg"
        - secretVolume:
            mountPath: "/home/jenkins/.gnupg"
            secretName: "jenkins-release-gpg"
        workspaceVolume:
          emptyDirWorkspaceVolume:
            memory: false
```
